-- 1. Tabla de Likes y Restricciones
CREATE TABLE IF NOT EXISTS public.post_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(post_id, user_id)
);

-- Habilitar RLS en post_likes
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Gestión propia de likes" ON public.post_likes
FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 2. Trigger para Sincronizar Contador de Likes
CREATE OR REPLACE FUNCTION public.sync_post_likes_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE public.posts SET likes = likes + 1 WHERE id = NEW.post_id;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE public.posts SET likes = GREATEST(0, likes - 1) WHERE id = OLD.post_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_sync_post_likes ON public.post_likes;
CREATE TRIGGER tr_sync_post_likes
AFTER INSERT OR DELETE ON public.post_likes
FOR EACH ROW EXECUTE PROCEDURE public.sync_post_likes_count();

-- 3. Configurar Expiración Automática
ALTER TABLE public.posts 
ALTER COLUMN expires_at SET DEFAULT (now() + interval '15 days');

-- 4. Política RLS para Ocultar Expirados
DROP POLICY IF EXISTS "Lectura pública posts" ON public.posts;
CREATE POLICY "Lectura pública posts" ON public.posts 
FOR SELECT TO authenticated 
USING (expires_at > now() OR expires_at IS NULL);

-- 5. Inicialización de datos existentes
-- Asegurar que todos los posts tengan una fecha de expiración si no la tienen
UPDATE public.posts SET expires_at = (created_at + interval '15 days') WHERE expires_at IS NULL;
-- En caso de que created_at también sea null (poco probable), usar now()
UPDATE public.posts SET expires_at = (now() + interval '15 days') WHERE expires_at IS NULL;

-- Sincronizar contador de likes basado en la tabla relacional
UPDATE public.posts p 
SET likes = (SELECT count(*) FROM public.post_likes WHERE post_id = p.id);
