-- COMPREHENSIVE SUPABASE DATABASE FIX SCRIPT
-- Objective: Ensure full CRUD capabilities for authenticated users while maintaining security.

-- 1. UTILITY: FUNCTION TO RESET POLICIES
-- This function will drop all existing policies on a table to ensure a clean slate.
CREATE OR REPLACE FUNCTION public.reset_table_policies(t_name text) RETURNS void AS $$
DECLARE
    pol record;
BEGIN
    FOR pol IN SELECT policyname FROM pg_policies WHERE tablename = t_name AND schemaname = 'public' LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', pol.policyname, t_name);
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- 2. APPLY TRANSFORMATIONS TO ALL DATA TABLES
DO $$ 
DECLARE 
    tbl text;
    tables_list text[] := ARRAY[
        'cursos', 'estudiantes', 'actividades', 'calificaciones', 'secuencias', 
        'incidencias', 'recuperaciones', 'eventos', 'descriptores_rubrica', 
        'niveles_puntaje', 'criterios_cotejo', 'docentes', 
        'evaluaciones_rubrica', 'evaluaciones_cotejo'
    ];
BEGIN
    FOREACH tbl IN ARRAY tables_list LOOP
        -- Ensure user_id column exists (just in case)
        BEGIN
            EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS user_id uuid DEFAULT auth.uid() REFERENCES auth.users(id)', tbl);
        EXCEPTION WHEN others THEN RAISE NOTICE 'Could not add user_id to %', tbl;
        END;

        -- Ensure user_id has the correct default and is NOT NULL
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN user_id SET DEFAULT auth.uid()', tbl);
        -- Note: We only set NOT NULL if there aren't existing NULLs. 
        -- Based on previous analysis, we'll try to set it but wrap in a block.
        BEGIN
            EXECUTE format('UPDATE public.%I SET user_id = auth.uid() WHERE user_id IS NULL', tbl);
            EXECUTE format('ALTER TABLE public.%I ALTER COLUMN user_id SET NOT NULL', tbl);
        EXCEPTION WHEN others THEN RAISE NOTICE 'Could not set user_id NOT NULL on %', tbl;
        END;

        -- Reset all policies on the table
        PERFORM public.reset_table_policies(tbl);

        -- Enable RLS
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);

        -- Create granular policies
        EXECUTE format('CREATE POLICY "select_own_%I" ON public.%I FOR SELECT TO authenticated USING (auth.uid() = user_id)', tbl, tbl);
        EXECUTE format('CREATE POLICY "insert_own_%I" ON public.%I FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id)', tbl, tbl);
        EXECUTE format('CREATE POLICY "update_own_%I" ON public.%I FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id)', tbl, tbl);
        EXECUTE format('CREATE POLICY "delete_own_%I" ON public.%I FOR DELETE TO authenticated USING (auth.uid() = user_id)', tbl, tbl);
    END LOOP;
END $$;

-- 3. SPECIAL HANDLING FOR POSTS (Comunidad)
-- Posts should be readable by all authenticated users but only editable by the owner.
SELECT public.reset_table_policies('posts');
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_all_posts" ON public.posts FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert_own_posts" ON public.posts FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own_posts" ON public.posts FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "delete_own_posts" ON public.posts FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- 4. SPECIAL HANDLING FOR PERFILES
-- Profiles table often uses 'id' instead of 'user_id' for the user link.
SELECT public.reset_table_policies('perfiles');
ALTER TABLE public.perfiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select_own_profile" ON public.perfiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "insert_own_profile" ON public.perfiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "update_own_profile" ON public.perfiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- 5. IDENTITY COLUMNS REINFORCEMENT
-- Ensure primary keys don't block inserts due to identity restrictions.
DO $$
DECLARE
    r record;
BEGIN
    FOR r IN (
        SELECT tablename 
        FROM pg_tables 
        WHERE schemaname = 'public' 
        AND tablename IN ('cursos', 'estudiantes', 'actividades', 'posts', 'secuencias', 'incidencias', 'eventos', 'descriptores_rubrica', 'criterios_cotejo', 'docentes', 'evaluaciones_rubrica', 'evaluaciones_cotejo')
    ) LOOP
        BEGIN
            EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', r.tablename);
        EXCEPTION WHEN others THEN 
            BEGIN
                EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET GENERATED BY DEFAULT', r.tablename);
            EXCEPTION WHEN others THEN RAISE NOTICE 'Identity for % already configured or not applicable', r.tablename;
            END;
        END;
    END LOOP;
END $$;

-- 6. INDEXES FOR PERFORMANCE
-- Ensure every table has an index on user_id for fast lookups.
CREATE INDEX IF NOT EXISTS idx_cursos_user_id ON public.cursos(user_id);
CREATE INDEX IF NOT EXISTS idx_estudiantes_user_id ON public.estudiantes(user_id);
CREATE INDEX IF NOT EXISTS idx_actividades_user_id ON public.actividades(user_id);
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON public.posts(user_id);
CREATE INDEX IF NOT EXISTS idx_calificaciones_user_id ON public.calificaciones(user_id);
CREATE INDEX IF NOT EXISTS idx_secuencias_user_id ON public.secuencias(user_id);
CREATE INDEX IF NOT EXISTS idx_incidencias_user_id ON public.incidencias(user_id);
CREATE INDEX IF NOT EXISTS idx_recuperaciones_user_id ON public.recuperaciones(user_id);
CREATE INDEX IF NOT EXISTS idx_eventos_user_id ON public.eventos(user_id);

-- 7. CLEANUP
DROP FUNCTION IF EXISTS public.reset_table_policies(text);

-- 8. GRANT PERMISSIONS
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- MISSION COMPLETE: The database is now fully CRUD-ready for authenticated users.
