-- SCRIPT DE REPARACIÓN DE BASE DE DATOS Y PERMISOS DE SUPABASE
-- Ejecuta este script en el editor SQL de tu panel de control de Supabase (Dashboard -> SQL Editor)

-- 1. Crear la tabla 'docentes' si hace falta (se detectó ausente en la caché de esquemas)
CREATE TABLE IF NOT EXISTS public.docentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre TEXT,
    asignatura TEXT,
    avatar_color TEXT DEFAULT '#3b82f6',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Habilitar RLS en docentes
ALTER TABLE public.docentes ENABLE ROW LEVEL SECURITY;

-- Crear políticas básicas para la tabla de docentes
DROP POLICY IF EXISTS "Gestión propia de docentes" ON public.docentes;
CREATE POLICY "Gestión propia de docentes" ON public.docentes
FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Lectura pública docentes" ON public.docentes;
CREATE POLICY "Lectura pública docentes" ON public.docentes
FOR SELECT TO authenticated
USING (true);


-- 2. Crear/reparar la función helper 'is_course_teacher' con SECURITY DEFINER
-- Al usar SECURITY DEFINER evitamos recursión infinita en las políticas RLS y errores de permisos.
CREATE OR REPLACE FUNCTION public.is_course_teacher(p_curso_id bigint)
RETURNS boolean AS $$
DECLARE
    current_user_id uuid;
BEGIN
    current_user_id := auth.uid();
    IF current_user_id IS NULL THEN
        RETURN false;
    END IF;
    
    RETURN EXISTS (
        SELECT 1 FROM public.cursos
        WHERE id = p_curso_id AND user_id = current_user_id
    ) OR EXISTS (
        SELECT 1 FROM public.curso_docentes
        WHERE curso_id = p_curso_id AND docente_id = current_user_id
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Sobrecarga para soportar tipo INTEGER si alguna tabla lo usa en lugar de BIGINT
CREATE OR REPLACE FUNCTION public.is_course_teacher(p_curso_id integer)
RETURNS boolean AS $$
BEGIN
    RETURN public.is_course_teacher(p_curso_id::bigint);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 3. Otorgar permisos de ejecución para los roles de la API
GRANT EXECUTE ON FUNCTION public.is_course_teacher(bigint) TO anon, authenticated, public;
GRANT EXECUTE ON FUNCTION public.is_course_teacher(integer) TO anon, authenticated, public;


-- 4. Asegurar accesibilidad general del API de PostgREST sobre las tablas y secuencias
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated, anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, anon;
