-- ============================================================
-- FASE 3: LISTA DE COTEJO DE RECUPERACIÓN
-- Modelo definitivo: indicadores fijos por BC, COLUMNAS = actividades
-- reales que cumplen las DOS condiciones (puntaje < 70 Y competencia
-- correspondiente al BC que se recupera). Columnas dinámicas.
-- MODELO DE ESTADOS (definitivo): solo existen DOS estados por celda:
--   ✓ = LOGRADO   (se persiste UNA fila en recuperaciones_cotejo)
--   vacío = NO LOGRADO  (NO se persiste nada; la AUSENCIA de fila ES el estado)
-- NO existe "X", NO existe "no evaluado", NO hay columna de estado.
-- Resultado BC = (# filas ✓ ÷ (indicadores × actividades aplicables)) × 100.
--
-- La recuperación es 100% independiente de la evaluación normal.
-- Las actividades SOLO se usan como filtro de columnas (solo lectura);
-- esta migración NO modifica actividades ni calificaciones.
-- Es ADITIVA e IDEMPOTENTE. NO borra ni altera datos existentes.
--
-- Ejecutar en: Supabase Dashboard -> SQL Editor.
-- IMPORTANTE: si ya ejecutaste una versión previa de este archivo,
-- avísalo antes de ejecutar (requeriría ALTER, no CREATE).
-- ============================================================

-- 1) Cabecera: añadir id identity a recuperaciones (aditivo).
--    Estado REAL verificado en BD (26/08/2026): recuperaciones NO tiene
--    columna id; PK actual = (estudiante_id, curso_id, bc, periodo, asignatura);
--    existen registros (11). ADD COLUMN id es seguro (columna nueva; las filas
--    existentes se numeran automáticamente con la secuencia de identidad).
--    UNIQUE: REQUERIDO porque recuperaciones_cotejo.recuperacion_id es FK a id
--    (toda FK necesita unicidad en la columna referenciada).
--    No rompe el onConflict actual de la app y no se modifica la PK existente.
ALTER TABLE public.recuperaciones
ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE;

-- 2) Tabla hija: una fila por EVIDENCIA LOGRADA (✓).
--    La AUSENCIA de fila = celda vacía = NO LOGRADO (vacío NO se persiste).
--    No existe estado "X" ni "no evaluado"; el registro en sí es el logro.
--    actividad_id = actividad REAL que originó la evidencia.
CREATE TABLE IF NOT EXISTS public.recuperaciones_cotejo (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recuperacion_id bigint NOT NULL REFERENCES public.recuperaciones(id) ON DELETE CASCADE,
    estudiante_id   bigint  NOT NULL,
    curso_id        bigint  NOT NULL,
    bc              smallint NOT NULL CHECK (bc BETWEEN 1 AND 4),
    periodo         text    NOT NULL,
    asignatura      text    NOT NULL DEFAULT '',
    indicador       text    NOT NULL,
    actividad_id    bigint NOT NULL REFERENCES public.actividades(id) ON DELETE CASCADE,
    shared_course_id text   NULL,
    user_id         uuid    NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    -- UNIQUE (recuperacion_id, bc, indicador, actividad_id): bc es redundante
    -- con la cabecera pero protege contra filas incoherentes (bc != cabecera).
    CONSTRAINT uq_recuperacion_cotejo_celda UNIQUE (recuperacion_id, bc, indicador, actividad_id)
);

-- 3) Índices de lectura
CREATE INDEX IF NOT EXISTS idx_recuperaciones_cotejo_curso
    ON public.recuperaciones_cotejo (curso_id);
CREATE INDEX IF NOT EXISTS idx_recuperaciones_cotejo_estudiante
    ON public.recuperaciones_cotejo (estudiante_id, periodo);
CREATE INDEX IF NOT EXISTS idx_recuperaciones_cotejo_actividad
    ON public.recuperaciones_cotejo (actividad_id);

-- 4) RLS
ALTER TABLE public.recuperaciones_cotejo ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_recuperaciones_cotejo" ON public.recuperaciones_cotejo;
CREATE POLICY "select_own_recuperaciones_cotejo"
    ON public.recuperaciones_cotejo FOR SELECT TO authenticated
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_recuperaciones_cotejo" ON public.recuperaciones_cotejo;
CREATE POLICY "insert_own_recuperaciones_cotejo"
    ON public.recuperaciones_cotejo FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_recuperaciones_cotejo" ON public.recuperaciones_cotejo;
CREATE POLICY "update_own_recuperaciones_cotejo"
    ON public.recuperaciones_cotejo FOR UPDATE TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_recuperaciones_cotejo" ON public.recuperaciones_cotejo;
CREATE POLICY "delete_own_recuperaciones_cotejo"
    ON public.recuperaciones_cotejo FOR DELETE TO authenticated
    USING (auth.uid() = user_id);

-- Lectura del centro (mismo patrón que migration_panel_centro.sql:220)
DROP POLICY IF EXISTS "recuperaciones_cotejo_select_centro" ON public.recuperaciones_cotejo;
CREATE POLICY "recuperaciones_cotejo_select_centro"
    ON public.recuperaciones_cotejo FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.cursos cu
            JOIN public.centro_roles cr ON cr.centro_id = cu.centro_id
            WHERE cu.id = recuperaciones_cotejo.curso_id
            AND cr.user_id = auth.uid()
            AND cr.rol IN ('director', 'administrador')
        )
    );

-- 5) Permisos
GRANT SELECT, INSERT, UPDATE, DELETE ON public.recuperaciones_cotejo TO authenticated;
GRANT ALL ON public.recuperaciones_cotejo TO service_role;

-- 6) Verificación
SELECT tablename, policyname, cmd
FROM pg_policies
WHERE tablename IN ('recuperaciones', 'recuperaciones_cotejo')
  AND schemaname = 'public'
ORDER BY tablename, policyname;