-- MIGRACIÓN DE BASE DE DATOS
-- Creación de la tabla 'planificacion_recursos' para asociar recursos externos a planificaciones

CREATE TABLE IF NOT EXISTS public.planificacion_recursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planificacion_id BIGINT NOT NULL REFERENCES public.secuencias(id) ON DELETE CASCADE,
    titulo TEXT NOT NULL,
    url TEXT NOT NULL,
    tipo TEXT NOT NULL,
    orden INT DEFAULT 0,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.planificacion_recursos ENABLE ROW LEVEL SECURITY;

-- Política de visualización: El usuario puede ver sus propios recursos.
CREATE POLICY "Users can view their own resources" 
ON public.planificacion_recursos 
FOR SELECT 
USING (auth.uid() = user_id);

-- Política de inserción: El usuario puede insertar sus propios recursos.
CREATE POLICY "Users can insert their own resources" 
ON public.planificacion_recursos 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Política de actualización: El usuario puede actualizar sus propios recursos.
CREATE POLICY "Users can update their own resources" 
ON public.planificacion_recursos 
FOR UPDATE 
USING (auth.uid() = user_id);

-- Política de borrado: El usuario puede borrar sus propios recursos.
CREATE POLICY "Users can delete their own resources" 
ON public.planificacion_recursos 
FOR DELETE 
USING (auth.uid() = user_id);
