-- MIGRATION: PANEL DE CENTRO EDUCATIVO (Entorno independiente)
-- 1) Tareas asignadas por el centro a sus docentes
-- 2) Asignaciones de cada tarea por docente
-- 3) Enlace de notificaciones a tareas
-- 4) Políticas RLS de lectura para directores/administradores del centro
--
-- ORDEN IMPORTANTE:
--   1. Crear TODAS las tablas (tareas, tarea_asignaciones)
--   2. Vínculo en notificaciones
--   3. Crear TODAS las políticas RLS (dependen de que las tablas existan)
--   4. Índices de rendimiento

-- ════════════════════════════════════════════════════════════════════
-- 1. TABLAS
-- ════════════════════════════════════════════════════════════════════

-- 1.1 TABLA TAREAS
CREATE TABLE IF NOT EXISTS public.tareas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    centro_id UUID NOT NULL REFERENCES public.centros(id) ON DELETE CASCADE,
    titulo TEXT NOT NULL,
    descripcion TEXT DEFAULT '',
    fecha_limite DATE,
    estado TEXT NOT NULL DEFAULT 'pendiente'
        CHECK (estado IN ('pendiente', 'completada', 'cancelada')),
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 1.2 TABLA TAREA_ASIGNACIONES
CREATE TABLE IF NOT EXISTS public.tarea_asignaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tarea_id BIGINT NOT NULL REFERENCES public.tareas(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    estado TEXT NOT NULL DEFAULT 'pendiente'
        CHECK (estado IN ('pendiente', 'completada')),
    fecha_completado TIMESTAMP WITH TIME ZONE,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE (tarea_id, user_id)
);

ALTER TABLE public.tareas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tarea_asignaciones ENABLE ROW LEVEL SECURITY;

-- ════════════════════════════════════════════════════════════════════
-- 2. NOTIFICACIONES: vínculo opcional con una tarea
-- ════════════════════════════════════════════════════════════════════
ALTER TABLE public.notificaciones ADD COLUMN IF NOT EXISTS tarea_id BIGINT;

-- ════════════════════════════════════════════════════════════════════
-- 3. POLÍTICAS RLS
--    (todas se crean después de que existan tareas y tarea_asignaciones)
-- ════════════════════════════════════════════════════════════════════

-- 3.1 POLÍTICAS DE TAREAS
-- Lectura: directores/administradores del centro, docentes asignados o creador
CREATE POLICY "tareas_select_centro"
ON public.tareas FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.centro_roles cr
        WHERE cr.centro_id = tareas.centro_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
    OR EXISTS (
        SELECT 1 FROM public.tarea_asignaciones ta
        WHERE ta.tarea_id = tareas.id
        AND ta.user_id = auth.uid()
        AND ta.activo
    )
    OR created_by = auth.uid()
);

-- Escritura: directores/administradores del centro o creador
CREATE POLICY "tareas_manage_centro"
ON public.tareas FOR ALL TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.centro_roles cr
        WHERE cr.centro_id = tareas.centro_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
    OR created_by = auth.uid()
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.centro_roles cr
        WHERE cr.centro_id = tareas.centro_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
    OR created_by = auth.uid()
);

-- 3.2 POLÍTICAS DE TAREA_ASIGNACIONES
-- Lectura: directores/administradores del centro o el docente asignado
CREATE POLICY "asignaciones_select_centro"
ON public.tarea_asignaciones FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.tareas t
        JOIN public.centro_roles cr ON cr.centro_id = t.centro_id
        WHERE t.id = tarea_asignaciones.tarea_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
    OR user_id = auth.uid()
);

-- Inserción: directores/administradores del centro
CREATE POLICY "asignaciones_insert_centro"
ON public.tarea_asignaciones FOR INSERT TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.tareas t
        JOIN public.centro_roles cr ON cr.centro_id = t.centro_id
        WHERE t.id = tarea_asignaciones.tarea_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
);

-- Actualización: el propio docente (completar) o el centro
CREATE POLICY "asignaciones_update_centro"
ON public.tarea_asignaciones FOR UPDATE TO authenticated
USING (
    user_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.tareas t
        JOIN public.centro_roles cr ON cr.centro_id = t.centro_id
        WHERE t.id = tarea_asignaciones.tarea_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
)
WITH CHECK (
    user_id = auth.uid()
    OR EXISTS (
        SELECT 1 FROM public.tareas t
        JOIN public.centro_roles cr ON cr.centro_id = t.centro_id
        WHERE t.id = tarea_asignaciones.tarea_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
);

-- Eliminación: directores/administradores del centro
CREATE POLICY "asignaciones_delete_centro"
ON public.tarea_asignaciones FOR DELETE TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.tareas t
        JOIN public.centro_roles cr ON cr.centro_id = t.centro_id
        WHERE t.id = tarea_asignaciones.tarea_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
);

-- 3.3 POLÍTICAS DE LECTURA PARA EL CENTRO (director / administrador)
--      Permiten al panel de centro consultar la información de sus docentes.

-- CURSOS: el centro ve los cursos de su institución
CREATE POLICY "cursos_select_centro"
ON public.cursos FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.centro_roles cr
        WHERE cr.centro_id = cursos.centro_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
);

-- ESTUDIANTES: el centro ve los estudiantes de sus cursos
CREATE POLICY "estudiantes_select_centro"
ON public.estudiantes FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.cursos cu
        JOIN public.centro_roles cr ON cr.centro_id = cu.centro_id
        WHERE cu.id = estudiantes.curso_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
);

-- ACTIVIDADES: el centro ve las actividades de sus cursos
CREATE POLICY "actividades_select_centro"
ON public.actividades FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.cursos cu
        JOIN public.centro_roles cr ON cr.centro_id = cu.centro_id
        WHERE cu.id = actividades.curso_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
);

-- CALIFICACIONES: el centro ve las calificaciones de sus cursos
CREATE POLICY "calificaciones_select_centro"
ON public.calificaciones FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.cursos cu
        JOIN public.centro_roles cr ON cr.centro_id = cu.centro_id
        WHERE cu.id = calificaciones.curso_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
);

-- RECUPERACIONES: el centro ve las recuperaciones de sus cursos
CREATE POLICY "recuperaciones_select_centro"
ON public.recuperaciones FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.cursos cu
        JOIN public.centro_roles cr ON cr.centro_id = cu.centro_id
        WHERE cu.id = recuperaciones.curso_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
);

-- INCIDENCIAS: el centro ve las incidencias registradas en sus cursos
CREATE POLICY "incidencias_select_centro"
ON public.incidencias FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.cursos cu
        JOIN public.centro_roles cr ON cr.centro_id = cu.centro_id
        WHERE cu.shared_course_id = incidencias.shared_course_id
        AND cr.user_id = auth.uid()
        AND cr.rol IN ('director', 'administrador')
    )
);

-- PERFILES: los miembros del centro pueden consultar los perfiles del centro
CREATE POLICY "perfiles_select_centro"
ON public.perfiles FOR SELECT TO authenticated
USING (
    centro_id IN (
        SELECT centro_id FROM public.perfiles
        WHERE user_id = auth.uid()
    )
);

-- ════════════════════════════════════════════════════════════════════
-- 4. ÍNDICES DE RENDIMIENTO
-- ════════════════════════════════════════════════════════════════════
CREATE INDEX IF NOT EXISTS idx_tareas_centro_id ON public.tareas(centro_id);
CREATE INDEX IF NOT EXISTS idx_tareas_estado ON public.tareas(estado);
CREATE INDEX IF NOT EXISTS idx_tarea_asignaciones_tarea_id ON public.tarea_asignaciones(tarea_id);
CREATE INDEX IF NOT EXISTS idx_tarea_asignaciones_user_id ON public.tarea_asignaciones(user_id);
CREATE INDEX IF NOT EXISTS idx_cursos_centro_id ON public.cursos(centro_id);
