-- ============================================================================
-- MIGRACIÓN v2 FINAL: Calendario Académico MINERD — tabla dedicada + semilla
--
-- ALCANCE ESTRICTO: este script trabaja EXCLUSIVAMENTE sobre
-- public.calendario_minerd (creación, índices, RLS, siembra).
--
--   public.eventos           -> NO se modifica: sin DDL, sin DML, sin tocar
--                               políticas ni user_id NOT NULL.
--   public.calendario_minerd -> Calendario académico oficial MINERD:
--                               fuente global reutilizable, SIN user_id,
--                               una sola fila por evento real.
--
-- SEGURIDAD DE EJECUCIÓN:
--   * Todo el DDL es IF NOT EXISTS / OR REPLACE / DROP IF EXISTS.
--   * La siembra es UN INSERT atómico con guard NOT EXISTS ->
--     re-ejecutable N veces sin duplicados.
--   * Las únicas menciones a public.eventos en este archivo son consultas
--     READ-ONLY de verificación (sección 5).
--
-- TAXONOMÍA CANÓNICA DE TOKENS (contrato para el resolver de contextualización):
--   niveles[]       : 'SECUNDARIO' | 'TODOS' | 'NACIONAL' | 'EPJAM'
--   modalidades[]   : 'TODAS' | 'ACADEMICA' | 'TECNICO_PROFESIONAL' | 'ARTES'
--   destinatarios[] : 'DOCENTE' | 'ESTUDIANTE' | 'CENTRO_EDUCATIVO' | 'TODOS'
--   prioridad       : 'CRITICA' | 'ALTA' | 'MEDIA' | 'BAJA'
--   tipo            : 'academico' | 'evaluacion' | 'administrativo' |
--                     'planificacion' | 'feriado' | 'receso' |
--                     'institucional' | 'conmemoracion' | 'otro'
--
-- Convención de fechas: ISO YYYY-MM-DD. Un día => fecha_inicio = fecha_fin.
-- anio_academico = año de INICIO del ciclo (ciclo 2026-2027 -> 2026).
-- ============================================================================

-- ============================================================================
-- SECCIÓN 1 — TABLA public.calendario_minerd (esquema oficial completo)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.calendario_minerd (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo                text NOT NULL,
    descripcion           text,
    fecha_inicio          date NOT NULL,
    fecha_fin             date NOT NULL,
    tipo                  text NOT NULL DEFAULT 'otro',
    prioridad             text,
    niveles               text[] NOT NULL DEFAULT '{TODOS}',
    modalidades           text[] NOT NULL DEFAULT '{TODAS}',
    destinatarios         text[] NOT NULL DEFAULT '{TODOS}',
    es_condicional        boolean NOT NULL DEFAULT false,
    condicion             jsonb,
    es_automatico         boolean NOT NULL DEFAULT false,
    requiere_recordatorio boolean NOT NULL DEFAULT false,
    bloquea_planificacion boolean NOT NULL DEFAULT false,
    modulo_destino        text,
    anio_academico        integer NOT NULL,
    metadata              jsonb,
    activo                boolean NOT NULL DEFAULT true,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),

    -- Integridad del modelo oficial
    CONSTRAINT calendario_minerd_rango_valido CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT calendario_minerd_tipo_valido CHECK (tipo IN (
      'academico','evaluacion','administrativo','planificacion',
      'feriado','receso','institucional','conmemoracion','otro')),
    CONSTRAINT calendario_minerd_prioridad_valida CHECK (
      prioridad IS NULL OR prioridad IN ('CRITICA','ALTA','MEDIA','BAJA'))
);

-- updated_at automático
CREATE OR REPLACE FUNCTION public.calendario_minerd_touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_calendario_minerd_updated_at ON public.calendario_minerd;
CREATE TRIGGER trg_calendario_minerd_updated_at
  BEFORE UPDATE ON public.calendario_minerd
  FOR EACH ROW EXECUTE FUNCTION public.calendario_minerd_touch_updated_at();

-- ============================================================================
-- SECCIÓN 2 — ÍNDICES (volumen pequeño: decenas por año; sin GIN)
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_calendario_minerd_anio
  ON public.calendario_minerd (anio_academico);

-- Índice principal de consultas del calendario (rango ∩ mes visible, activos)
CREATE INDEX IF NOT EXISTS idx_calendario_minerd_rango
  ON public.calendario_minerd (fecha_inicio, fecha_fin)
  WHERE activo = true;

-- Solicitado explícitamente; complementa al parcial anterior para
-- conteos administrativos sobre inactivos.
CREATE INDEX IF NOT EXISTS idx_calendario_minerd_activo
  ON public.calendario_minerd (activo);

-- ============================================================================
-- SECCIÓN 3 — RLS: solo lectura para autenticados; escritura administrativa
-- ============================================================================
ALTER TABLE public.calendario_minerd ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS calendario_minerd_select_autenticados ON public.calendario_minerd;
CREATE POLICY calendario_minerd_select_autenticados ON public.calendario_minerd
  FOR SELECT TO authenticated
  USING (activo = true);

-- Sin políticas INSERT/UPDATE/DELETE para authenticated (denegado por defecto).
-- Carga/administración vía SQL administrativo o service_role.

-- ============================================================================
-- SECCIÓN 4 — SEMILLA 2026-2027 (35 eventos, idempotente:
--            identidad lógica = anio_academico + titulo + fecha_inicio)
-- Layout VALUES: (titulo, descripcion, fecha_inicio, fecha_fin, tipo,
--   prioridad, niveles, modalidades, destinatarios, es_condicional, condicion,
--   es_automatico, requiere_recordatorio, bloquea_planificacion,
--   modulo_destino, anio_academico, metadata)
-- ============================================================================

INSERT INTO public.calendario_minerd (
  titulo, descripcion, fecha_inicio, fecha_fin, tipo, prioridad,
  niveles, modalidades, destinatarios,
  es_condicional, condicion, es_automatico, requiere_recordatorio,
  bloquea_planificacion, modulo_destino, anio_academico, metadata
)
SELECT
  v.titulo,
  v.descripcion,
  v.fecha_inicio,
  v.fecha_fin,
  v.tipo,
  v.prioridad,
  v.niveles::text[] AS niveles,             -- VALUES infiere text: cast requerido
  v.modalidades::text[] AS modalidades,     -- idem
  v.destinatarios::text[] AS destinatarios, -- idem
  v.es_condicional,
  v.condicion::jsonb,
  v.es_automatico,
  v.requiere_recordatorio,
  v.bloquea_planificacion,
  v.modulo_destino,
  v.anio_academico,
  v.metadata::jsonb
FROM (VALUES

  -- ===================== 1. INICIO Y CIERRE DEL AÑO ACADÉMICO =====================
  ('Inicio año laboral docente', NULL, DATE '2026-08-03', DATE '2026-08-03',
    'academico', 'CRITICA', '{SECUNDARIO,TODOS}', '{TODAS}', '{DOCENTE}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[9,22]}'),

  ('Inicio docencia estudiantes', NULL, DATE '2026-08-24', DATE '2026-08-24',
    'academico', 'CRITICA', '{SECUNDARIO}', '{TODAS}', '{ESTUDIANTE}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[9,22]}'),

  ('Cierre P1 — 1er reporte de calificaciones', NULL, DATE '2026-10-30', DATE '2026-10-30',
    'evaluacion', 'CRITICA', '{SECUNDARIO}', '{TODAS}', '{DOCENTE,ESTUDIANTE}',
    false, NULL, true, true, true, 'calificaciones', 2026, '{"fuente_paginas":[13,31]}'),

  ('Cierre P2 — 2do reporte de calificaciones', NULL, DATE '2027-01-29', DATE '2027-01-29',
    'evaluacion', 'CRITICA', '{SECUNDARIO}', '{TODAS}', '{DOCENTE,ESTUDIANTE}',
    false, NULL, true, true, false, 'calificaciones', 2026, '{"fuente_paginas":[13,43]}'),

  ('Cierre P3 — 3er reporte de calificaciones', NULL, DATE '2027-03-31', DATE '2027-03-31',
    'evaluacion', 'CRITICA', '{SECUNDARIO}', '{TODAS}', '{DOCENTE,ESTUDIANTE}',
    false, NULL, true, true, false, 'calificaciones', 2026, '{"fuente_paginas":[13,50]}'),

  ('Cierre P4 — 4to reporte de calificaciones', NULL, DATE '2027-06-01', DATE '2027-06-01',
    'evaluacion', 'CRITICA', '{SECUNDARIO}', '{TODAS}', '{DOCENTE,ESTUDIANTE}',
    false, NULL, true, true, false, 'calificaciones', 2026,
    '{"fuente_paginas":[13,62],"aplicacion":"1RO_A_5TO"}'),

  ('Entrega de calificaciones finales del Nivel Secundario',
    '6to grado y cierre general.', DATE '2027-06-08', DATE '2027-06-08',
    'evaluacion', 'CRITICA', '{SECUNDARIO}', '{TODAS}', '{DOCENTE,ESTUDIANTE}',
    false, NULL, true, false, false, 'calificaciones', 2026, '{"fuente_paginas":[62]}'),

  ('Fin de docencia — año lectivo estudiantes', NULL, DATE '2027-06-18', DATE '2027-06-18',
    'academico', 'CRITICA', '{SECUNDARIO}', '{TODAS}', '{ESTUDIANTE}',
    false, NULL, true, false, true, 'planificacion', 2026, '{"fuente_paginas":[13,22],"nota":"bloqueo de planificación POSTERIOR a esta fecha"}'),

  ('Fin año laboral docente / inicio vacaciones docentes', NULL, DATE '2027-06-29', DATE '2027-06-29',
    'academico', 'ALTA', '{SECUNDARIO}', '{TODAS}', '{DOCENTE}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[9,13]}'),

  ('Fin vacaciones docentes', NULL, DATE '2027-07-30', DATE '2027-07-30',
    'administrativo', 'MEDIA', '{TODOS}', '{TODAS}', '{DOCENTE}',
    false, NULL, false, false, false, NULL, 2026, '{"fuente_paginas":[9],"integracion":"consulta"}'),

  ('Reintegro docente / inicio jornada de capacitación de verano', NULL, DATE '2027-08-02', DATE '2027-08-02',
    'administrativo', 'MEDIA', '{TODOS}', '{TODAS}', '{DOCENTE}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[9],"integracion":"apertura nuevo año académico"}'),

  -- ========================= 2. RECUPERACIÓN PEDAGÓGICA =========================
  ('Recuperación pedagógica P1', NULL, DATE '2026-11-02', DATE '2027-01-29',
    'planificacion', 'MEDIA', '{SECUNDARIO}', '{TODAS}', '{DOCENTE}',
    false, NULL, false, false, false, NULL, 2026, '{"fuente_paginas":[34],"integracion":"consulta"}'),

  ('Recuperación pedagógica P2', NULL, DATE '2027-02-01', DATE '2027-03-30',
    'planificacion', 'MEDIA', '{SECUNDARIO}', '{TODAS}', '{DOCENTE}',
    false, NULL, false, false, false, NULL, 2026, '{"fuente_paginas":[46],"integracion":"consulta"}'),

  ('Recuperación pedagógica P3', NULL, DATE '2027-04-01', DATE '2027-05-30',
    'planificacion', 'MEDIA', '{SECUNDARIO}', '{TODAS}', '{DOCENTE}',
    false, NULL, false, false, false, NULL, 2026, '{"fuente_paginas":[54],"integracion":"consulta"}'),

  ('Período especial de recuperación de docencia',
    'Aplica únicamente a centros educativos con más de 5% de docencia perdida.',
    DATE '2027-06-21', DATE '2027-06-29',
    'administrativo', 'MEDIA', '{SECUNDARIO,TODOS}', '{TODAS}', '{CENTRO_EDUCATIVO}',
    true, '{"tipo":"docencia_perdida","operador":">","umbral_porcentaje":5}',
    false, false, false, NULL, 2026, '{"fuente_paginas":[62,9],"integracion":"alerta_condicional"}'),

  -- ============================ 3. FERIADOS NACIONALES ============================
  ('Restauración de la República', 'Feriado nacional.', DATE '2026-08-16', DATE '2026-08-16',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12]}'),

  ('Ntra. Sra. de las Mercedes', NULL, DATE '2026-09-24', DATE '2026-09-24',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12]}'),

  ('Día de la Constitución', 'Trasladado del 6 de noviembre.', DATE '2026-11-09', DATE '2026-11-09',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12],"fecha_original":"2026-11-06"}'),

  ('Navidad', NULL, DATE '2026-12-25', DATE '2026-12-25',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12]}'),

  ('Año Nuevo', NULL, DATE '2027-01-01', DATE '2027-01-01',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12]}'),

  ('Día de Reyes', 'Trasladado del 6 de enero.', DATE '2027-01-04', DATE '2027-01-04',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12],"fecha_original":"2027-01-06"}'),

  ('Ntra. Sra. de la Altagracia', NULL, DATE '2027-01-21', DATE '2027-01-21',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12]}'),

  ('Natalicio Juan Pablo Duarte', 'Trasladado del 26 de enero.', DATE '2027-01-25', DATE '2027-01-25',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12],"fecha_original":"2027-01-26"}'),

  ('Independencia Nacional', NULL, DATE '2027-02-27', DATE '2027-02-27',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12]}'),

  ('Viernes Santo', NULL, DATE '2027-03-26', DATE '2027-03-26',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12,50]}'),

  ('Día Internacional del Trabajo', 'Trasladado del 1 de mayo.', DATE '2027-05-03', DATE '2027-05-03',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12],"fecha_original":"2027-05-01"}'),

  ('Corpus Christi', NULL, DATE '2027-05-27', DATE '2027-05-27',
    'feriado', 'ALTA', '{NACIONAL}', '{TODAS}', '{TODOS}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[12]}'),

  -- =========================== 4. RECESOS ESCOLARES ===========================
  ('Vacaciones de Navidad — estudiantes', NULL, DATE '2026-12-18', DATE '2027-01-06',
    'receso', 'ALTA', '{TODOS}', '{TODAS}', '{ESTUDIANTE}',
    false, NULL, true, false, true, 'planificacion', 2026, '{"fuente_paginas":[39]}'),

  ('Semana Santa', 'Receso escolar. Reinicio el 29/03/2027.', DATE '2027-03-22', DATE '2027-03-28',
    'receso', 'ALTA', '{TODOS}', '{TODAS}', '{ESTUDIANTE}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[50]}'),

  -- ========================== 5. PRUEBAS NACIONALES ==========================
  -- Dos bloques contiguos (05-06 y 07-08/08) => rango continuo 05..08/08/2026.
  ('Segunda Convocatoria Pruebas Nacionales', NULL, DATE '2026-08-05', DATE '2026-08-08',
    'evaluacion', 'ALTA', '{SECUNDARIO,EPJAM}', '{ACADEMICA,TECNICO_PROFESIONAL,ARTES}', '{ESTUDIANTE}',
    false, NULL, true, false, false, NULL, 2026,
    '{"fuente_paginas":[22,23],"segmentos":["2026-08-05/2026-08-06","2026-08-07/2026-08-08"]}'),

  ('Tercera Convocatoria Pruebas Nacionales', NULL, DATE '2026-11-12', DATE '2026-11-13',
    'evaluacion', 'ALTA', '{SECUNDARIO}', '{ACADEMICA,TECNICO_PROFESIONAL,ARTES}', '{ESTUDIANTE}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[35]}'),

  ('Primera Convocatoria Pruebas Nacionales', 'Correspondiente al año siguiente.',
    DATE '2027-06-22', DATE '2027-06-25',
    'evaluacion', 'ALTA', '{SECUNDARIO,EPJAM}', '{TODAS}', '{ESTUDIANTE}',
    false, NULL, true, false, false, NULL, 2026, '{"fuente_paginas":[62,63]}'),

  -- ==================== 6. EVENTOS INSTITUCIONALES POR MODALIDAD ====================
  ('Semana vocacional 3er grado — Modalidad Técnico Profesional', NULL,
    DATE '2027-01-21', DATE '2027-01-23',
    'institucional', 'MEDIA', '{SECUNDARIO}', '{TECNICO_PROFESIONAL}', '{ESTUDIANTE}',
    false, NULL, false, true, false, NULL, 2026, '{"fuente_paginas":[42]}'),

  ('Orientación 3er grado para selección de menciones — Modalidad en Artes', NULL,
    DATE '2026-11-12', DATE '2026-11-15',
    'institucional', 'MEDIA', '{SECUNDARIO}', '{ARTES}', '{ESTUDIANTE}',
    false, NULL, false, true, false, NULL, 2026, '{"fuente_paginas":[35]}'),

  -- ============================== 7. CONMEMORACIÓN ==============================
  ('Día de la Evaluación', 'Último miércoles de octubre.', DATE '2026-10-28', DATE '2026-10-28',
    'conmemoracion', 'BAJA', '{NACIONAL}', '{TODAS}', '{DOCENTE,ESTUDIANTE}',
    false, NULL, false, true, false, NULL, 2026, '{"fuente_paginas":[29,30]}')

) AS v(titulo, descripcion, fecha_inicio, fecha_fin, tipo, prioridad,
       niveles, modalidades, destinatarios,
       es_condicional, condicion, es_automatico, requiere_recordatorio,
       bloquea_planificacion, modulo_destino, anio_academico, metadata)
WHERE NOT EXISTS (
  SELECT 1 FROM public.calendario_minerd m
  WHERE m.anio_academico = v.anio_academico
    AND m.titulo = v.titulo
    AND m.fecha_inicio = v.fecha_inicio
);

-- ============================================================================
-- SECCIÓN 5 — VERIFICACIONES OBLIGATORIAS (ejecutar y revisar resultados)
-- Nota: las comprobaciones sobre public.eventos son SOLO LECTURA
-- (catálogos del sistema); este archivo jamás la modifica.
-- ============================================================================

-- (1) Total MINERD 2026-2027 —— esperado: 35
SELECT COUNT(*) AS total_2026 FROM public.calendario_minerd WHERE anio_academico = 2026;

-- Distribución por tipo —— esperado:
-- academico=5 · administrativo=4 · conmemoracion=1 · evaluacion=7 · feriado=12 ·
-- institucional=2 · planificacion=3 · receso=2
SELECT tipo, COUNT(*) FROM public.calendario_minerd WHERE anio_academico = 2026 GROUP BY tipo ORDER BY tipo;

-- (2) Duplicados —— esperado: 0 filas
SELECT titulo, COUNT(*) FROM public.calendario_minerd WHERE anio_academico = 2026
GROUP BY titulo HAVING COUNT(*) > 1;

-- (3) Rangos inválidos —— esperado: 0 filas (además lo garantiza el CHECK)
SELECT id, titulo, fecha_inicio, fecha_fin FROM public.calendario_minerd
WHERE fecha_fin < fecha_inicio;

-- (4) Condicionales —— esperado: exactamente 1
--     ('Período especial de recuperación de docencia')
SELECT id, titulo, condicion FROM public.calendario_minerd WHERE es_condicional = true;

-- (5) Campos obligatorios incompletos —— esperado: 0 filas
SELECT id, titulo FROM public.calendario_minerd WHERE anio_academico = 2026 AND (
  prioridad IS NULL OR cardinality(niveles) = 0
  OR cardinality(modalidades) = 0 OR cardinality(destinatarios) = 0
);

-- (6) Distribución de prioridades —— esperado exacto:
--     CRITICA=8 · ALTA=18 · MEDIA=8 · BAJA=1
SELECT prioridad, COUNT(*) FROM public.calendario_minerd WHERE anio_academico = 2026
GROUP BY prioridad ORDER BY COUNT(*) DESC;

-- (7) RLS activa —— esperado: relrowsecurity = true
SELECT relrowsecurity, relforcerowsecurity FROM pg_class
WHERE oid = 'public.calendario_minerd'::regclass;

-- (8) Política SELECT para authenticated —— esperado: 1 fila
SELECT policyname, cmd, roles FROM pg_policies WHERE tablename = 'calendario_minerd';

-- (9) Rangos multi-día —— esperado: 11 filas
SELECT titulo, fecha_inicio, fecha_fin FROM public.calendario_minerd
WHERE anio_academico = 2026 AND fecha_fin > fecha_inicio ORDER BY fecha_inicio;

-- (10) public.eventos intacta — SOLO LECTURA (informativo):
--  10.a Estado de RLS y políticas actuales de eventos
--       IMPORTANTE: si ves columnas/políticas heredadas de la migración v1
--       fallida (p.ej. política 'eventos_select_autenticados' o columna
--       'niveles'), provienen de esa corrida anterior, NO de este script.
--       Se eliminan ejecutando el archivo opcional cleanup_eventos_v1_opcional.sql
SELECT c.relrowsecurity,
       COALESCE(array_agg(p.policyname) FILTER (WHERE p.policyname IS NOT NULL), '{}') AS politicas_actuales
FROM pg_class c
LEFT JOIN pg_policies p ON p.tablename = 'eventos'
WHERE c.oid = 'public.eventos'::regclass
GROUP BY c.relrowsecurity;

--  10.b Conteo de filas de eventos: regístralo ANTES y DESPUÉS de correr este
--       archivo; debe ser IDÉNTICO (aquí no se inserta nada en eventos).
SELECT COUNT(*) AS total_filas_eventos FROM public.eventos;

-- (11) Cero eventos MINERD dentro de public.eventos —— esperado: 0
SELECT COUNT(*) AS minerd_en_eventos
FROM public.eventos e
JOIN public.calendario_minerd m ON m.titulo = e.titulo;

-- (12) IDEMPOTENCIA: vuelve a ejecutar TODO este archivo y re-evalúa (1)+(2).
--      Total debe seguir siendo 35 y duplicados 0.
