-- SCRIPT DE BASE DE DATOS: SISTEMA DE RECUPERACIÓN DE CONTRASEÑA
-- Ejecuta este script en el editor SQL de Supabase (Dashboard -> SQL Editor)

-- 1. Tabla de tokens de recuperación de contraseña
CREATE TABLE IF NOT EXISTS public.recuperacion_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    token TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    estado TEXT DEFAULT 'activo' NOT NULL CHECK (estado IN ('activo', 'usado', 'revocado'))
);

-- Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE public.recuperacion_tokens ENABLE ROW LEVEL SECURITY;

-- Nota: Como el backend se conectará usando el rol de administrador (service_role),
-- no necesitamos políticas públicas de lectura/escritura en esta tabla. Esto evita
-- que usuarios malintencionados accedan a los tokens mediante la API directa de Supabase.
-- Por precaución, denegamos explícitamente todo acceso a anon y authenticated.
DROP POLICY IF EXISTS "Denegar acceso a tokens para anon y authenticated" ON public.recuperacion_tokens;

-- 2. Tabla para auditoría de eventos de seguridad
CREATE TABLE IF NOT EXISTS public.auditoria_recuperacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    email TEXT,
    ip_address TEXT NOT NULL,
    evento TEXT NOT NULL, -- 'solicitud_intentada', 'solicitud_enviada', 'token_validado', 'token_invalido', 'contrasena_restablecida', 'fuerza_bruta_detectada'
    detalles JSONB,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE public.auditoria_recuperacion ENABLE ROW LEVEL SECURITY;

-- 3. Índices de rendimiento y optimización de búsquedas y limpieza
CREATE INDEX IF NOT EXISTS idx_recuperacion_tokens_token ON public.recuperacion_tokens(token);
CREATE INDEX IF NOT EXISTS idx_recuperacion_tokens_user_id ON public.recuperacion_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_recuperacion_tokens_active ON public.recuperacion_tokens(expires_at, estado) WHERE estado = 'activo';
CREATE INDEX IF NOT EXISTS idx_auditoria_recuperacion_ip_time ON public.auditoria_recuperacion(ip_address, created_at);
CREATE INDEX IF NOT EXISTS idx_auditoria_recuperacion_email_time ON public.auditoria_recuperacion(email, created_at);

-- 4. Permisos mínimos para garantizar el acceso al rol service_role (backend)
GRANT ALL ON TABLE public.recuperacion_tokens TO service_role;
GRANT ALL ON TABLE public.auditoria_recuperacion TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- 5. Crear una función de utilidad para revocar tokens antiguos de un usuario
-- Esto permite invalidar en cascada cualquier otro token activo cuando se solicita uno nuevo
-- o cuando se completa satisfactoriamente el restablecimiento de contraseña.
CREATE OR REPLACE FUNCTION public.revocar_tokens_activos(p_user_id uuid)
RETURNS void AS $$
BEGIN
    UPDATE public.recuperacion_tokens
    SET estado = 'revocado'
    WHERE user_id = p_user_id AND estado = 'activo';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION public.revocar_tokens_activos(uuid) TO service_role;

-- 6. Función para obtener el user_id a partir del correo
CREATE OR REPLACE FUNCTION public.get_user_id_by_email(p_email text)
RETURNS uuid AS $$
DECLARE
    v_user_id uuid;
BEGIN
    SELECT id INTO v_user_id FROM auth.users WHERE email = p_email LIMIT 1;
    RETURN v_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Revocar ejecución pública y restringir a service_role por seguridad
REVOKE EXECUTE ON FUNCTION public.get_user_id_by_email(text) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_id_by_email(text) TO service_role;

