-- ============================================================================
-- EVIDENCIAS — Portafolio del estudiante + bandeja docente
-- ============================================================================
-- QUE EXISTE Y SE REUTILIZA (nada de esto se duplica)
-- ----------------------------------------------------------------------------
--   estudiantes        dueño del trabajo. NO tiene user_id ni centro_id, asi que
--                      la identidad del estudiante en el Portal SIEMPRE llega
--                      por portal_accesos.estudiante_id.
--   actividades        la "Actividad/Ficha" que ya usan Agenda, Rubrica, Cotejo
--                      y Sellos. Trae curso_id, asignatura, fecha, periodo y
--                      plan_ficha_id -> pc_notas(id). Una evidencia cuelga de
--                      ESA fila: no se crea una tabla de actividades nueva ni se
--                      duplica la ficha.
--   pc_notas           el titulo de la ficha, reached por actividades.plan_ficha_id.
--   portal_accesos      acceso del estudiante (centro, pin, activo).
--   portal_sesiones     session_token -> acceso_id. Es el unico credencial que
--                      viaja desde el Portal.
--   is_course_teacher  helper de autorizacion que ya usan las politicas de
--                      actividades/cursos (fix_db_permissions.sql). Es la
--                      separacion centro -> curso -> estudiante -> evidencia.
--   SELLOS_INFO        catalogo de 6 sellos que vive en src/screens/Sellos.tsx.
--                      La columna `sello` de esta tabla NO inventa una escala
--                      nueva: acepta exactamente los mismos 6 valores, y el
--                      mismo PNG de public/sellos/ se pinta en la UI.
--
-- QUE NO EXISTE (verificado: evidences/entregas/adjuntos -> PGRST205)
-- ----------------------------------------------------------------------------
--   No hay ninguna tabla de archivos de estudiantes. `portal_get_evidencias`
--   devuelve CALIFICACIONES pedagogicas, no archivos. `tarea_docente
--   .archivos_entrega` pertenece al modulo institucional, no a los cursos.
--   Tampoco hay bucket para esto (solo hay `avatars` y `registros`).
--   Por eso esta es la unica tabla y el unico bucket que se crean.
--
-- DONDE VIVE LA SEGURIDAD
-- ----------------------------------------------------------------------------
--   El bucket `evidencias` es privado y la TABLA esta cerrada por RLS, pero hay
--   una limitacion de plataforma que conviene escribir en mayusculas en vez de
--   adornar con una propiedad que no se tiene:
--
--   El Portal NO tiene JWT: el estudiante no existe en auth.users, solo tiene un
--   session_token. Sin un backend que firme URLs no hay forma de emitir una
--   signed URL para anon, y este frontend es estatico (no llama a
--   server/server.js en ningun punto). Por eso la politica de SELECT del bucket
--   tiene que abrirse a `anon`, porque sin ella el alumnus no puede ni previsualizar
--   lo que acaba de subir.
--
--   CONSECUENCIA REAL, sin adornos: en Supabase Storage, conceder SELECT sobre
--   un bucket HABILITA EL LISTADO, no solo la lectura por clave. Es decir, quien
--   tenga la clave anon (que viaja en el bundle del frontend, o sea, es publica)
--   puede pedir la LISTA de objetos del bucket y obtener todos los nombres. El
--   nombre del objeto es un uuid v4, y ese uuid es la credencial: la garantia
--   real es "no se adivina", no "no se lista".
--
--   Que queda expuesto con esto: los archivos subidos por la via LOCAL. Las
--   evidencias de Drive NO pasan por este bucket en absoluto, asi que con Drive
--   como via principal el alcance de la exposicion se reduce a ese respaldo.
--
--   QUE HAY QUE HACER PARA CERRARLO DE VERDAD: desplegar server/ y mover la
--   lectura a createSignedUrl emitido alli, y pasar estas politicas a
--   `authenticated`. Es un cambio de dos lineas en la politica y una en el
--   cliente cuando exista ese backend. Hasta entonces, este bloque es el
--   conocimiento escrito del riesgo, no una garantia.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) TABLA
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.evidencias (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Identidad del trabajo. estudiante_id es NOT NULL: no hay evidencia huerfana.
    estudiante_id   BIGINT NOT NULL REFERENCES public.estudiantes(id) ON DELETE CASCADE,
    actividad_id    BIGINT NOT NULL REFERENCES public.actividades(id) ON DELETE CASCADE,
    -- Traido de actividades.plan_ficha_id al insertar. Nullable porque la
    -- actividad puede no estar anclada a una ficha.
    ficha_id        UUID REFERENCES public.pc_notas(id) ON DELETE SET NULL,
    -- Copia del curso/asignatura en el momento de la entrega. Sin esto, la
    -- bandeja docente tendria que deducir el curso desde la actividad, y una
    -- actividad reasignada dejaria las evidencias huerfanas de su grupo.
    curso_id        BIGINT NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
    asignatura      TEXT,

    nombre          TEXT NOT NULL,
    descripcion     TEXT,

    -- Origen. `drive` queda soportado por el modelo (drive_file_id/drive_url/
    -- thumbnail_url) pero la v1 no conecta Drive: se documenta aqui para que la
    -- integracion real entre despues sin cambiar el esquema.
    origen          TEXT NOT NULL DEFAULT 'storage'
                        CHECK (origen IN ('storage','drive')),
    storage_path    TEXT,
    drive_file_id   TEXT,
    drive_url       TEXT,
    mime_type       TEXT,
    tamano_bytes    BIGINT,
    -- Miniatura servida por Drive cuando venga de ahi. Para `storage` la
    -- miniatura es el propio archivo: no se duplica el binario en otra fila.
    thumbnail_url   TEXT,

    -- Revision. Dos estados, los que pide el flujo: no se inventan estados
    -- pedagogicos nuevos. El contenido del juicio vive en `sello`.
    estado          TEXT NOT NULL DEFAULT 'pendiente'
                        CHECK (estado IN ('pendiente','revisada')),
    sello           INTEGER CHECK (sello IS NULL OR sello IN (100,85,70,55,1,0)),
    comentario      TEXT,
    revisado_por    UUID,
    revisado_at     TIMESTAMPTZ,
    creado_por      UUID,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Una evidencia tiene SI o un archivo de CIELO o una referencia de Drive.
    -- Nunca los dos, nunca ninguno.
    CONSTRAINT evidencias_origen_obligatorio CHECK (
        (origen = 'storage' AND storage_path IS NOT NULL)
        OR (origen = 'drive'   AND drive_file_id IS NOT NULL)
    ),
    -- Sellar marca revisada, y viceversa: no se guarda un sello en una
    -- evidencia que sigue pendiente, ni se da por revisada sin juicio.
    CONSTRAINT evidencias_revision_coherente CHECK (
        (estado = 'pendiente' AND sello IS NULL AND revisado_at IS NULL)
        OR (estado = 'revisada'  AND sello IS NOT NULL)
    )
);

-- El indice que usa la bandeja: curso + orden por fecha de la actividad.
CREATE INDEX IF NOT EXISTS evidencias_curso_actividad_idx
    ON public.evidencias (curso_id, actividad_id);
-- El indice que usa el Portafolio del estudiante.
CREATE INDEX IF NOT EXISTS evidencias_estudiante_idx
    ON public.evidencias (estudiante_id, created_at DESC);
-- Filtro de pendientes/revisadas sin recorrer todo el curso.
CREATE INDEX IF NOT EXISTS evidencias_curso_estado_idx
    ON public.evidencias (curso_id, estado);

-- ----------------------------------------------------------------------------
-- 2) RLS DE LA TABLA
-- ----------------------------------------------------------------------------
-- El estudiante NUNCA toca esta tabla directamente: entra por las RPC
-- SECURITY DEFINER de la seccion 4, que validan el session_token. Asi no hace
-- falta ninguna politica que reliance en el anon, que seria justamente la
-- politica global que este feature no debe tener.
ALTER TABLE public.evidencias ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.evidencias FROM anon;

-- Autorizacion por curso Y asignatura, en un solo sitio.
--
-- `is_course_teacher(curso_id)` solo sabe de cursos: un co-docente de Matematica
-- que comparte curso con Lengua pasaria el filtro y podria leer (o sellar) el
-- trabajo de Lengua. Este helper baja un nivel mas y exige que ademas sea tutor
-- o que este vinculado a ESA asignatura.
--
-- Falla cerrado: si `p_asignatura` es NULL, la tercera rama no se cumple y solo
-- entra quien sea tutor. Es la eleccion segura para una columna nullable.
--
-- Es la MISMA regla que usan `docente_bandeja_evidencias` y
-- `docente_revisar_evidencia`, de modo que las RLS de la tabla y las RPC no
-- pueden discrepar: por mucho que se corrija una, la otra sigue cerrada.
CREATE OR REPLACE FUNCTION public.is_course_subject_teacher(p_curso_id BIGINT, p_asignatura TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT public.is_course_teacher(p_curso_id)
       AND (
            EXISTS (
                SELECT 1 FROM public.cursos c
                WHERE c.id = p_curso_id
                  AND (c.user_id = auth.uid() OR c.is_tutor_oficial IS TRUE)
            )
            OR EXISTS (
                SELECT 1 FROM public.curso_docentes cd
                WHERE cd.curso_id = p_curso_id
                  AND cd.docente_id = auth.uid()
                  AND cd.activo IS NOT FALSE
                  AND (cd.rol = 'tutor' OR cd.es_tutor IS TRUE)
            )
            OR EXISTS (
                SELECT 1 FROM public.curso_docentes cd
                WHERE cd.curso_id = p_curso_id
                  AND cd.docente_id = auth.uid()
                  AND cd.activo IS NOT FALSE
                  AND cd.asignatura IS NOT NULL
                  AND cd.asignatura = p_asignatura
            )
       );
$$;

REVOKE ALL ON FUNCTION public.is_course_subject_teacher(BIGINT, TEXT) FROM PUBLIC, anon;

-- Docente: solo lo que hay en sus cursos Y de su asignatura. Mismo helper que el
-- resto del modulo, mismo criterio que visibleActividades en App.tsx.
DROP POLICY IF EXISTS evidencias_select_docente ON public.evidencias;
CREATE POLICY evidencias_select_docente ON public.evidencias
    FOR SELECT TO authenticated
    USING (public.is_course_subject_teacher(curso_id, asignatura));

DROP POLICY IF EXISTS evidencias_update_docente ON public.evidencias;
CREATE POLICY evidencias_update_docente ON public.evidencias
    FOR UPDATE TO authenticated
    USING (public.is_course_subject_teacher(curso_id, asignatura))
    WITH CHECK (public.is_course_subject_teacher(curso_id, asignatura));

-- NO hay politica de DELETE para el docente, y el GRANT de la seccion 6 tampoco
-- le concede DELETE. La version anterior si lo hacia, en un comentario que
-- decia justo lo contrario ("el docente no borra el archivo del alumno").
-- Retirar una evidencia es decision del estudiante y solo mientras siga
-- pendiente; el docente revisa y sella, nada mas.

-- ----------------------------------------------------------------------------
-- 3) BUCKET
-- ----------------------------------------------------------------------------
-- Nombre de objeto con uuid v4 + extension. Sin curso, sin nombre y sin id de
-- estudiante en la URL: la URL no dice de quien es el trabajo.
INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('evidencias', 'evidencias', false, 26214400)
ON CONFLICT (id) DO UPDATE
    SET file_size_limit = EXCLUDED.file_size_limit,
        public = EXCLUDED.public;

-- El Portal escribe con la clave anon (no tiene JWT), asi que la escritura se
-- acota al bucket y al patron de nombre. No se puede subir a otros buckets.
DROP POLICY IF EXISTS evidencias_insert_storage ON storage.objects;
CREATE POLICY evidencias_insert_storage ON storage.objects
    FOR INSERT TO anon, authenticated
    WITH CHECK (
        bucket_id = 'evidencias'
        AND name ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.[a-z0-9]{1,5}$'
    );

-- Lectura. Ver el bloque 0: abrir SELECT a `anon` habilita tambien el LISTADO
-- del bucket, asi que la garantia real es que el nombre es un uuid no adivinable,
-- no que el bucket sea inenumerable. Se cierra a `authenticated` cuando exista
-- server/ y las URLs se firmen alli.
DROP POLICY IF EXISTS evidencias_select_storage ON storage.objects;
CREATE POLICY evidencias_select_storage ON storage.objects
    FOR SELECT TO anon, authenticated
    USING (bucket_id = 'evidencias');

DROP POLICY IF EXISTS evidencias_update_storage ON storage.objects;
CREATE POLICY evidencias_update_storage ON storage.objects
    FOR UPDATE TO anon, authenticated
    USING (bucket_id = 'evidencias')
    WITH CHECK (bucket_id = 'evidencias');

DROP POLICY IF EXISTS evidencias_delete_storage ON storage.objects;
CREATE POLICY evidencias_delete_storage ON storage.objects
    FOR DELETE TO anon, authenticated
    USING (bucket_id = 'evidencias');

-- ----------------------------------------------------------------------------
-- 4) LADO PORTAL — el estudiante y su Portafolio
-- ----------------------------------------------------------------------------
-- Identidad del Portal. Devuelve el estudiante SOLO si el token es valido, no
-- expirado y su acceso sigue activo. Cualquier otra cosa devuelve null y las
-- RPC de abajo cortan.
CREATE OR REPLACE FUNCTION public.evidencia_estudiante_del_portal(p_session_token UUID)
RETURNS public.estudiantes
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_id BIGINT;
BEGIN
    IF p_session_token IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT a.estudiante_id
      INTO v_id
      FROM public.portal_sesiones s
      JOIN public.portal_accesos a ON a.id = s.acceso_id
     WHERE s.session_token = p_session_token
       AND s.expires_at > NOW()
       AND a.active IS TRUE
     LIMIT 1;

    IF v_id IS NULL THEN
        RETURN NULL;
    END IF;

    DECLARE
        v_est public.estudiantes;
    BEGIN
        SELECT * INTO v_est FROM public.estudiantes e WHERE e.id = v_id;
        RETURN v_est;
    END;
END;
$$;

REVOKE ALL ON FUNCTION public.evidencia_estudiante_del_portal(UUID) FROM PUBLIC, anon;

-- 4.1) Portafolio: todo lo del estudiante, con la actividad y la ficha resueltas
-- para que la UI no tenga que hacer N joins.
CREATE OR REPLACE FUNCTION public.portal_listar_evidencias(p_session_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_est public.estudiantes;
BEGIN
    v_est := public.evidencia_estudiante_del_portal(p_session_token);
    IF v_est IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    RETURN COALESCE((
        SELECT jsonb_agg(
            jsonb_build_object(
                'id',            e.id,
                'nombre',        e.nombre,
                'descripcion',   e.descripcion,
                'estado',        e.estado,
                'sello',         e.sello,
                'created_at',    e.created_at,
                'updated_at',    e.updated_at,
                'origen',        e.origen,
                'storage_path',  e.storage_path,
                'drive_url',     e.drive_url,
                'thumbnail_url', e.thumbnail_url,
                'mime_type',     e.mime_type,
                'tamano_bytes',  e.tamano_bytes,
                'comentario',    e.comentario,
                'revisado_at',   e.revisado_at,
                'actividad_id',  e.actividad_id,
                'actividad',     COALESCE(a.nombre, 'Actividad'),
                'actividad_fecha', a.fecha,
                'periodo',       a.periodo,
                'asignatura',    COALESCE(e.asignatura, a.asignatura),
                'ficha_id',      e.ficha_id,
                'ficha',         f.titulo
            )
            ORDER BY e.created_at DESC
        )
        FROM public.evidencias e
        JOIN public.actividades a ON a.id = e.actividad_id
        LEFT JOIN public.pc_notas f ON f.id = e.ficha_id
        WHERE e.estudiante_id = v_est.id
    ), '[]'::JSONB);
END;
$$;

-- 4.2) Selector de actividad del Portafolio. Solo actividades del curso del
-- estudiante, agrupadas por ficha, ordenadas de la mas reciente a la mas
-- antigua. Devuelve ademas cuantas evidencias tiene ya el alumno en cada una,
-- que es el numero que la tarjeta del Portafolio muestra.
CREATE OR REPLACE FUNCTION public.portal_listar_actividades_para_evidencia(p_session_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_est public.estudiantes;
BEGIN
    v_est := public.evidencia_estudiante_del_portal(p_session_token);
    IF v_est IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    RETURN COALESCE((
        SELECT jsonb_agg(
            jsonb_build_object(
                'actividad_id',  a.id,
                'actividad',     COALESCE(a.nombre, 'Actividad'),
                'fecha',         a.fecha,
                'periodo',       a.periodo,
                'asignatura',    COALESCE(a.asignatura, c.asignatura),
                'ficha_id',      a.plan_ficha_id,
                'ficha',         f.titulo,
                'evidencias',    (
                                    SELECT COUNT(*)
                                    FROM public.evidencias e
                                    WHERE e.estudiante_id = v_est.id
                                      AND e.actividad_id = a.id
                                )
            )
            ORDER BY COALESCE(a.fecha, a.created_at::date) DESC NULLS LAST, a.id DESC
        )
        FROM public.actividades a
        JOIN public.cursos c ON c.id = a.curso_id
        LEFT JOIN public.pc_notas f ON f.id = a.plan_ficha_id
        WHERE a.curso_id = v_est.curso_id
          AND a.activo IS NOT FALSE
    ), '[]'::JSONB);
END;
$$;

-- 4.3) Crear evidencia. La ficha se deriva de la actividad: el cliente no la
-- elige, y asi no puede colgar una evidencia de una ficha que no le toca.
CREATE OR REPLACE FUNCTION public.portal_crear_evidencia(
    p_session_token   UUID,
    p_actividad_id    BIGINT,
    p_nombre          TEXT,
    p_origen          TEXT    DEFAULT 'storage',
    p_storage_path    TEXT    DEFAULT NULL,
    p_drive_file_id   TEXT    DEFAULT NULL,
    p_drive_url       TEXT    DEFAULT NULL,
    p_mime_type       TEXT    DEFAULT NULL,
    p_tamano_bytes    BIGINT  DEFAULT NULL,
    p_thumbnail_url   TEXT    DEFAULT NULL,
    p_descripcion     TEXT    DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_est    public.estudiantes;
    v_act    public.actividades;
    v_curso  public.cursos;
    v_id     BIGINT;
BEGIN
    v_est := public.evidencia_estudiante_del_portal(p_session_token);
    IF v_est IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    IF p_actividad_id IS NULL THEN
        RETURN jsonb_build_object('error', 'Selecciona la actividad o ficha de la evidencia');
    END IF;

    -- La actividad tiene que ser del curso del estudiante. Esta comparacion es
    -- la que impide que un alumno cuelgue trabajo en el curso de otro.
    SELECT a.* INTO v_act
    FROM public.actividades a
    JOIN public.cursos c ON c.id = a.curso_id
    WHERE a.id = p_actividad_id
      AND a.curso_id = v_est.curso_id
      AND a.activo IS NOT FALSE;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('error', 'La actividad no está disponible');
    END IF;

    SELECT * INTO v_curso FROM public.cursos c WHERE c.id = v_est.curso_id;

    IF p_origen NOT IN ('storage', 'drive') THEN
        RETURN jsonb_build_object('error', 'Origen de evidencia no válido');
    END IF;
    IF p_origen = 'storage' AND p_storage_path IS NULL THEN
        RETURN jsonb_build_object('error', 'Falta el archivo subido');
    END IF;
    IF p_origen = 'drive' AND p_drive_file_id IS NULL THEN
        RETURN jsonb_build_object('error', 'Falta la referencia de Google Drive');
    END IF;
    IF p_nombre IS NULL OR btrim(p_nombre) = '' THEN
        RETURN jsonb_build_object('error', 'Ponle un nombre a la evidencia');
    END IF;

    INSERT INTO public.evidencias (
        estudiante_id, actividad_id, ficha_id, curso_id, asignatura,
        nombre, descripcion, origen, storage_path, drive_file_id, drive_url,
        mime_type, tamano_bytes, thumbnail_url
    )
    VALUES (
        v_est.id, v_act.id, v_act.plan_ficha_id, v_act.curso_id,
        COALESCE(v_act.asignatura, v_curso.asignatura),
        btrim(p_nombre), NULLIF(btrim(COALESCE(p_descripcion, '')), ''), p_origen,
        p_storage_path, p_drive_file_id, p_drive_url,
        p_mime_type, p_tamano_bytes, p_thumbnail_url
    )
    RETURNING id INTO v_id;

    RETURN jsonb_build_object('id', v_id);
END;
$$;

-- 4.4) Retirar evidencia. Solo mientras siga pendiente: en cuanto el docente
-- sello, el trabajo ya fue evaluado y el alumno pierde el Retreat.
CREATE OR REPLACE FUNCTION public.portal_eliminar_evidencia(
    p_session_token UUID,
    p_evidencia_id  BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_est   public.estudiantes;
    v_path  TEXT;
BEGIN
    v_est := public.evidencia_estudiante_del_portal(p_session_token);
    IF v_est IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    SELECT e.storage_path INTO v_path
    FROM public.evidencias e
    WHERE e.id = p_evidencia_id
      AND e.estudiante_id = v_est.id
      AND e.estado = 'pendiente'
    FOR UPDATE;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('error', 'No se puede retirar esta evidencia');
    END IF;

    DELETE FROM public.evidencias WHERE id = p_evidencia_id;

    -- El binario lo borra el cliente con la ruta que devuelve esta RPC. Aqui no
    -- se toca storage: la fila es la fuente de verdad y su ruta es lo unico que
    -- el cliente puede conocer sin autorizacion.
    RETURN jsonb_build_object('ok', true, 'storage_path', v_path);
END;
$$;

REVOKE ALL ON FUNCTION public.portal_crear_evidencia(UUID, BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BIGINT, TEXT, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.portal_eliminar_evidencia(UUID, BIGINT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.portal_listar_evidencias(UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.portal_listar_actividades_para_evidencia(UUID) FROM PUBLIC, anon;

-- ----------------------------------------------------------------------------
-- 5) LADO DOCENTE — la bandeja global
-- ----------------------------------------------------------------------------
-- Una sola RPC trae la bandeja completa: actividades del curso con su cuenta de
-- evidencias y, dentro, las evidencias de cada estudiante con su nombre. Menos
-- viajes y, sobre todo, una sola decision de autorizacion.
--
-- El filtro de asignatura replica exactamente el criterio de
-- `visibleActividades` (App.tsx): un co-docente ve su asignatura; quien es
-- tutor del curso ve todas. Asi la bandeja no ensena trabajo de otra asignatura
-- aunque comparta curso.
CREATE OR REPLACE FUNCTION public.docente_bandeja_evidencias(
    p_curso_id  BIGINT,
    p_asignatura TEXT DEFAULT NULL,
    p_periodo   TEXT    DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_uid         UUID := auth.uid();
    v_curso       public.cursos;
    v_asignaturas TEXT[];
    -- Hay TRES casos y hay que distinguirlos, porque las dos versiones anteriores
    -- los mezclaban:
    --
    --   1. Tutor o dueno del curso     -> ve todas las asignaturas.
    --   2. Co-docente con N asignaturas -> ve solo esas N.
    --   3. Co-docente sin asignaturas   -> no ve nada.
    --
    -- El caso 3 es el que obliga a un booleano aparte. Se intentaba resolver con
    -- `v_asignaturas = '{}' OR ...`, y como el filtro que construye
    -- `v_asignaturas` descarta los NULL, un docente sin asignaturas se quedaba
    -- con el array vacio y esa comparacion le daba paso a TODO el curso.
    --
    -- Y en la version previa ademas se concatenaba
    -- `v_asignaturas := v_asignaturas || COALESCE(p_asignatura, v_curso.asignatura)`,
    -- lo que anulaba el filtro por completo: un co-docente de Matematica podia
    -- pedir `p_asignatura => 'Lengua Española'` y se le concedia, porque la
    -- asignatura que el mismo acababa de pedir entraba en la lista de las
    -- permitidas. `p_asignatura` PRESENTA y filtra; nunca amplia permisos.
    v_ver_todas BOOLEAN := FALSE;
BEGIN
    IF v_uid IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    IF NOT public.is_course_teacher(p_curso_id) THEN
        RETURN jsonb_build_object('error', 'No tienes acceso a este curso');
    END IF;

    SELECT * INTO v_curso FROM public.cursos c WHERE c.id = p_curso_id;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('error', 'Curso no encontrado');
    END IF;

    -- Asignaturas que puede ver este usuario en ESTE curso.
    SELECT COALESCE(array_agg(DISTINCT cd.asignatura) FILTER (WHERE cd.asignatura IS NOT NULL), '{}'::TEXT[])
      INTO v_asignaturas
    FROM public.curso_docentes cd
    WHERE cd.curso_id = p_curso_id
      AND cd.docente_id = v_uid
      AND cd.activo IS NOT FALSE;

    -- Caso 1. La misma definicion de tutor que usa el resto del modulo.
    IF EXISTS (
        SELECT 1 FROM public.cursos c
        WHERE c.id = p_curso_id
          AND (c.user_id = v_uid OR c.is_tutor_oficial IS TRUE)
    ) OR EXISTS (
        SELECT 1 FROM public.curso_docentes cd
        WHERE cd.curso_id = p_curso_id
          AND cd.docente_id = v_uid
          AND (cd.rol = 'tutor' OR cd.es_tutor IS TRUE)
          AND cd.activo IS NOT FALSE
    ) THEN
        v_ver_todas := TRUE;
    END IF;

    RETURN jsonb_build_object(
        'curso', jsonb_build_object(
            'id',        v_curso.id,
            'nombre',    v_curso.nombre,
            'grado',     v_curso.grado,
            'seccion',   v_curso.seccion,
            'periodo',   v_curso.periodo,
            'asignatura', p_asignatura
        ),
        'grupos', COALESCE((
            SELECT jsonb_agg(
                jsonb_build_object(
                    'actividad_id',   a.id,
                    'actividad',      COALESCE(a.nombre, 'Actividad'),
                    'fecha',          a.fecha,
                    'periodo',        a.periodo,
                    'asignatura',     COALESCE(a.asignatura, v_curso.asignatura),
                    'ficha_id',       a.plan_ficha_id,
                    'ficha',          f.titulo,
                    'total',          (SELECT COUNT(*) FROM public.evidencias x WHERE x.actividad_id = a.id),
                    'pendientes',     (SELECT COUNT(*) FROM public.evidencias x WHERE x.actividad_id = a.id AND x.estado = 'pendiente'),
                    'revisadas',      (SELECT COUNT(*) FROM public.evidencias x WHERE x.actividad_id = a.id AND x.estado = 'revisada'),
                    'evidencias', COALESCE((
                        SELECT jsonb_agg(
                            jsonb_build_object(
                                'id',            x.id,
                                'nombre',        x.nombre,
                                'estado',        x.estado,
                                'sello',         x.sello,
                                'comentario',    x.comentario,
                                'origen',        x.origen,
                                'storage_path',  x.storage_path,
                                'drive_url',     x.drive_url,
                                'thumbnail_url', x.thumbnail_url,
                                'mime_type',     x.mime_type,
                                'tamano_bytes',  x.tamano_bytes,
                                'created_at',    x.created_at,
                                'revisado_at',   x.revisado_at,
                                'estudiante_id', x.estudiante_id,
                                'estudiante',    btrim(COALESCE(es.nombre, '') || ' ' || COALESCE(es.apellido, '')),
                                'numero_lista',  es.numero_lista,
                                'estudiante_avatar_color', es.avatar_color
                            )
                            ORDER BY es.numero_lista NULLS LAST, es.nombre, x.created_at
                        )
                        FROM public.evidencias x
                        JOIN public.estudiantes es ON es.id = x.estudiante_id
                        WHERE x.actividad_id = a.id
                    ), '[]'::JSONB)
                )
                -- Mas reciente primero. La fecha de la actividad manda, que es
                -- la que el docente ya ve en Agenda; created_at desempata.
                ORDER BY COALESCE(a.fecha, a.created_at::date) DESC NULLS LAST, a.id DESC
            )
            FROM public.actividades a
            LEFT JOIN public.pc_notas f ON f.id = a.plan_ficha_id
            WHERE a.curso_id = p_curso_id
              AND a.activo IS NOT FALSE
              -- El filtro compara la asignatura RESUELTA, no la cruda. Si
              -- `actividades.asignatura` viniera vacia y se dejara pasar, un
              -- co-docente de Matematica veria en su bandeja una actividad sin
              -- asignatura que en realidad es de Lenguaje.
              --
              -- `v_ver_todas` sustituye al antiguo `v_asignaturas = '{}'`: vacio ya
              -- no significa "todo", significa "nada". Y si el cliente pide una
              -- asignatura concreta, tiene que estar entre las suyas.
              AND (v_ver_todas
                   OR (
                        COALESCE(a.asignatura, v_curso.asignatura) = ANY (v_asignaturas)
                        AND (p_asignatura IS NULL OR COALESCE(a.asignatura, v_curso.asignatura) = p_asignatura)
                   ))
              AND (p_periodo IS NULL OR a.periodo = p_periodo)
              AND EXISTS (SELECT 1 FROM public.evidencias x WHERE x.actividad_id = a.id)
        ), '[]'::JSONB)
    );
END;
$$;

-- 5.2) Sellar. Valida curso, valida que el sello sea uno de los 6 de CIELO y
-- deja la evidencia en `revisada`. Un UPDATE, no un INSERT: la fila ya existe y
-- el alumno la ve al instante.
CREATE OR REPLACE FUNCTION public.docente_revisar_evidencia(
    p_evidencia_id BIGINT,
    p_sello        INTEGER,
    p_comentario   TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_uid     UUID := auth.uid();
    v_guardado INTEGER;
BEGIN
    IF v_uid IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    IF p_sello IS NULL OR p_sello NOT IN (100, 85, 70, 55, 1, 0) THEN
        RETURN jsonb_build_object('error', 'Elige un sello de CIELO');
    END IF;

    -- `is_course_subject_teacher(curso_id, asignatura)` va en el WHERE y no en un
    -- IF previo: asi la fila que no es del usuario no se actualiza y cae en
    -- NO_DATA_FOUND, en vez de distinguir "no existe" de "no es tuya".
    UPDATE public.evidencias
       SET estado       = 'revisada',
           sello        = p_sello,
           comentario   = NULLIF(btrim(COALESCE(p_comentario, '')), ''),
           revisado_por = v_uid,
           revisado_at  = NOW(),
           updated_at   = NOW()
     WHERE id = p_evidencia_id
       AND public.is_course_subject_teacher(curso_id, asignatura)
    RETURNING sello INTO v_guardado;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('error', 'No se encontró la evidencia en tus cursos');
    END IF;

    RETURN jsonb_build_object('ok', true, 'sello', v_guardado, 'estado', 'revisada');
END;
$$;

-- 5.3) Cursos con bandeja. Alimenta el selector de la subseccion sin que el
-- cliente tenga que adivinar a quien pertenece cada curso.
CREATE OR REPLACE FUNCTION public.docente_cursos_con_evidencias()
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_uid UUID := auth.uid();
BEGIN
    IF v_uid IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    RETURN COALESCE((
        SELECT jsonb_agg(
            jsonb_build_object(
                'curso_id',  c.id,
                'grado',     c.grado,
                'seccion',   c.seccion,
                'periodo',   c.periodo,
                'color',     c.color,
                -- Solo las asignaturas que este docente puede ver en el curso. La
                -- version anterior listaba TODAS las del curso, con lo que el
                -- desplegable de la bandeja revelaba los nombres de las materias de
                -- otros companeros aunque no se le pudiera abrir su trabajo.
                'asignaturas', (
                    SELECT CASE
                        WHEN c.user_id = v_uid OR c.is_tutor_oficial IS TRUE OR EXISTS (
                            SELECT 1 FROM public.curso_docentes t
                            WHERE t.curso_id = c.id AND t.docente_id = v_uid
                              AND (t.rol = 'tutor' OR t.es_tutor IS TRUE)
                              AND t.activo IS NOT FALSE
                        ) THEN (
                            SELECT jsonb_agg(DISTINCT a.asignatura ORDER BY a.asignatura)
                            FROM public.actividades a
                            WHERE a.curso_id = c.id AND a.asignatura IS NOT NULL
                        )
                        ELSE (
                            SELECT jsonb_agg(DISTINCT a.asignatura ORDER BY a.asignatura)
                            FROM public.actividades a
                            WHERE a.curso_id = c.id
                              AND a.asignatura IS NOT NULL
                              AND a.asignatura IN (
                                  SELECT cd.asignatura FROM public.curso_docentes cd
                                  WHERE cd.curso_id = c.id
                                    AND cd.docente_id = v_uid
                                    AND cd.asignatura IS NOT NULL
                                    AND cd.activo IS NOT FALSE
                              )
                        )
                    END
                ),
                'pendientes', (SELECT COUNT(*) FROM public.evidencias x WHERE x.curso_id = c.id AND x.estado = 'pendiente')
            )
            ORDER BY c.periodo, c.grado, c.seccion
        )
        FROM public.cursos c
        WHERE public.is_course_teacher(c.id)
          AND EXISTS (SELECT 1 FROM public.evidencias x WHERE x.curso_id = c.id)
    ), '[]'::JSONB);
END;
$$;

REVOKE ALL ON FUNCTION public.docente_bandeja_evidencias(BIGINT, TEXT, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.docente_revisar_evidencia(BIGINT, INTEGER, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.docente_cursos_con_evidencias() FROM PUBLIC, anon;

-- ----------------------------------------------------------------------------
-- 6) GRANTS
-- ----------------------------------------------------------------------------
-- Las RPC de arriba siguen siendo SECURITY DEFINER, asi que el cliente solo
-- necesita poder llamarlas. La tabla, no: sigue cerrada por RLS.
GRANT EXECUTE ON FUNCTION public.portal_listar_evidencias(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_listar_actividades_para_evidencia(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_crear_evidencia(UUID, BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BIGINT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_eliminar_evidencia(UUID, BIGINT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.docente_bandeja_evidencias(BIGINT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.docente_revisar_evidencia(BIGINT, INTEGER, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.docente_cursos_con_evidencias() TO authenticated;

-- SELECT y UPDATE, nunca DELETE: el docente revisa, el alumno retira.
GRANT SELECT, UPDATE ON public.evidencias TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.evidencias_id_seq TO authenticated;
