-- ============================================================================
-- PORTAL DEL ESTUDIANTE — GOOGLE DRIVE
-- ============================================================================
-- QUE REUTILIZA
-- ----------------------------------------------------------------------------
--   evidencia_estudiante_del_portal(p_session_token)
--       Helper de identidad que creo 20260926130000_evidencias.sql. Devuelve el
--       estudiante SOLO si el token es valido y su acceso sigue activo. Todas
--       las RPC de este archivo arrancan por ahi, asi que la identidad del
--       estudiante no se puede falsificar: no se acepta un estudiante_id como
--       parametro en ningun sitio.
--
--   evidencias.origen = 'drive', drive_file_id, drive_url, thumbnail_url
--       El modelo de la v1 ya reservaba esas columnas. Este archivo las llena de
--       verdad; no cambia el contrato de la tabla ni sus CHECK.
--
-- QUE NO HAY Y POR QUE
-- ----------------------------------------------------------------------------
--   NO hay columna de token, ni access_token, ni refresh_token, ni cookie, ni
--   fila de credenciales. Es deliberado y es una decision del proyecto, no una
--  carencia: el token de Drive vive SOLO en memoria del navegador, igual que
--   hace el docente en src/lib/googleDrive.ts. Se reconecta al entrar.
--   Consecuencia asumida: si el alumno cierra la pestana, hay que volver a
--   autorizar. A cambio, no hay un token de un menor guardado en una base de
--   datos, que es el peor de los tres desenlaces posibles. Cuando exista
--   server/ desplegado, aqui se anade el refresh token cifrado.
--
-- REPARTO DE RESPONSABILIDAD CON GOOGLE
-- ----------------------------------------------------------------------------
--   Google Drive es el Dueño del archivo. Supabase es el indice.
--   · El binario NUNCA se copia a storage.buckets 'evidencias'.
--   · Supabase guarda: drive_file_id (la clave real), nombre, mime, tamano,
--     thumbnail_url y la carpeta de la que salio.
--   · Si el alumno borra el archivo en Drive, la evidencia queda huerfana. Por eso
--     `drive_file_id` es NOT NULL y la columna se conserva aunque Drive ya no
--     sirva el archivo: la UI muestra el aviso en vez de romper.
--   · El acceso al archivo SIEMPRE pasa por el token del alumno. El docente
--     jamas ve el archivo de Drive del alumno con su propia cuenta: en la bandeja
--     ve el `drive_url` del alumno, que solo abre si el propio alumno mantiene su
--     carpeta compartida. Ver `docente_bandeja_evidencias` mas abajo.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) CONEXION
-- ----------------------------------------------------------------------------
-- Una fila por estudiante. Describe QUE Drive esta conectado, no COMO se
-- autoriza. `cielo_root_id` es el id real de la carpeta CIELO del alumno y es
-- NULL hasta que el alumno confirme su primera asignatura: conectar no crea
-- nada.
CREATE TABLE IF NOT EXISTS public.portal_drive_conexion (
    estudiante_id  BIGINT PRIMARY KEY REFERENCES public.estudiantes(id) ON DELETE CASCADE,
    email          TEXT,
    -- Id REAL devuelto por la API de Google. A partir de aqui la carpeta raiz
    -- se busca por id, nunca por el texto "CIELO".
    cielo_root_id  TEXT,
    conectado_en   TIMESTAMPTZ,
    activo         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.portal_drive_conexion IS
    'Conexion Drive del estudiante. No guarda tokens: el token vive solo en memoria del navegador.';

-- ----------------------------------------------------------------------------
-- 2) CARPETAS POR ASIGNATURA
-- ----------------------------------------------------------------------------
-- La estructura CIELO/<Asignatura> vive en el Drive del alumno, y aqui solo su
-- indice. El UNIQUE (estudiante_id, asignatura) es la garantia de que una
-- asignatura no se configure dos veces con carpetas distintas.
--
-- `asignatura` guarda el id del catalogo (src/constants/asignaturas.ts), no el
-- texto visible. El texto se guarda aparte porque es el nombre de la carpeta en
-- Drive y porque el catalogo puede renombrar una asignatura sin que eso deba
-- mover una carpeta ya creada ni romper la relacion con evidencias existentes.
CREATE TABLE IF NOT EXISTS public.portal_drive_carpeta (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id     BIGINT NOT NULL REFERENCES public.estudiantes(id) ON DELETE CASCADE,
    asignatura        TEXT NOT NULL,
    asignatura_nombre TEXT NOT NULL,
    -- Id real de la carpeta en Drive. Es la clave de todo: la evidencia lo
    -- referencia y la UI abre el Drive con el, sin depender del nombre.
    drive_folder_id   TEXT NOT NULL,
    -- false = la carpeta ya existia en el Drive del alumno y solo se enlazo.
    -- true = CIELO la creo al confirmar la asignatura.
    creado_en_drive   BOOLEAN NOT NULL DEFAULT FALSE,
    archivos          INTEGER NOT NULL DEFAULT 0,
    creado_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT portal_drive_carpeta_unica UNIQUE (estudiante_id, asignatura)
);

CREATE INDEX IF NOT EXISTS portal_drive_carpeta_estudiante_idx
    ON public.portal_drive_carpeta (estudiante_id);

-- Enlace evidencia -> carpeta de origen. SET NULL y no CASCADE: si el alumno
-- desconecta Drive la evidencia se conserva; solo se pierde la carpeta.
ALTER TABLE public.evidencias
    ADD COLUMN IF NOT EXISTS drive_carpeta_id BIGINT
        REFERENCES public.portal_drive_carpeta(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS evidencias_drive_carpeta_idx
    ON public.evidencias (drive_carpeta_id);

-- ----------------------------------------------------------------------------
-- 3) RLS
-- ----------------------------------------------------------------------------
-- Igual que evidencias: el estudiante NUNCA toca estas tablas directamente,
-- entra por RPC SECURITY DEFINER que validan el session_token. Por eso no hay
-- ni una politica para anon.
ALTER TABLE public.portal_drive_conexion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portal_drive_carpeta  ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.portal_drive_conexion FROM anon;
REVOKE ALL ON public.portal_drive_carpeta  FROM anon;

-- La tabla no se expone a authenticated: un docente autenticado no tiene por
-- que ver a que Drive esta conectado un alumno. Lo que si ve es su bandeja, y
-- ahi solo le llega lo de sus cursos.

-- ----------------------------------------------------------------------------
-- 4) RPC DEL PORTAL
-- ----------------------------------------------------------------------------
-- 4.1) Estado de la conexion + carpetas ya configuradas. Una sola llamada
-- alimenta toda la pantalla: si esta conectada, que Drive es, que carpeta raiz
-- tiene y que asignaturas ya organizo.
CREATE OR REPLACE FUNCTION public.portal_drive_estado(p_session_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_est   public.estudiantes;
    v_con   public.portal_drive_conexion;
BEGIN
    v_est := public.evidencia_estudiante_del_portal(p_session_token);
    IF v_est IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    SELECT * INTO v_con
    FROM public.portal_drive_conexion
    WHERE estudiante_id = v_est.id
      AND activo IS TRUE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object(
            'conectado', FALSE,
            'email', NULL,
            'cielo_root_id', NULL,
            'carpetas', '[]'::JSONB
        );
    END IF;

    RETURN jsonb_build_object(
        'conectado', TRUE,
        'email', v_con.email,
        'cielo_root_id', v_con.cielo_root_id,
        'conectado_en', v_con.conectado_en,
        'carpetas', COALESCE((
            SELECT jsonb_agg(
                jsonb_build_object(
                    'id',              c.id,
                    'asignatura',      c.asignatura,
                    'asignatura_nombre', c.asignatura_nombre,
                    'drive_folder_id', c.drive_folder_id,
                    'creado_en_drive', c.creado_en_drive,
                    'archivos',        c.archivos
                )
                ORDER BY c.asignatura_nombre
            )
            FROM public.portal_drive_carpeta c
            WHERE c.estudiante_id = v_est.id
        ), '[]'::JSONB)
    );
END;
$$;

-- 4.2) Registrar la conexion. p_cielo_root_id llega NULL en el primer clic de
-- "Conectar": eso es lo que garantiza que conectar no cree carpetas. La raiz
-- solo se rellena mas tarde, en 4.3, cuando el alumno confirma su primera
-- asignatura.
CREATE OR REPLACE FUNCTION public.portal_drive_registrar_conexion(
    p_session_token   UUID,
    p_email           TEXT,
    p_cielo_root_id   TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_est public.estudiantes;
BEGIN
    v_est := public.evidencia_estudiante_del_portal(p_session_token);
    IF v_est IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    -- Solo se acepta un root_id si no habia otro. Si ya existe, conservar el
    -- antiguo: si el alumno reorganiza Drive a mano y borra CIELO, re-conectar
    -- no debe repuntar la raiz a una carpeta distinta y dejar huerfanas las
    -- carpetas de asignatura ya enlazadas.
    INSERT INTO public.portal_drive_conexion (
        estudiante_id, email, cielo_root_id, conectado_en, activo, updated_at
    )
    VALUES (
        v_est.id,
        NULLIF(btrim(COALESCE(p_email, '')), ''),
        NULLIF(btrim(COALESCE(p_cielo_root_id, '')), ''),
        NOW(), TRUE, NOW()
    )
    ON CONFLICT (estudiante_id) DO UPDATE
       SET email         = EXCLUDED.email,
           conectado_en  = EXCLUDED.conectado_en,
           activo        = TRUE,
           updated_at    = EXCLUDED.updated_at,
           -- COALESCE mantiene el root previo si esta vez llega NULL.
           cielo_root_id = COALESCE(public.portal_drive_conexion.cielo_root_id, EXCLUDED.cielo_root_id);

    RETURN jsonb_build_object('ok', TRUE);
END;
$$;

-- 4.3) Anotar la carpeta raiz CIELO. Se llama desde la confirmacion de la
-- primera asignatura, no al conectar. A partir de este momento la raiz se
-- localiza SIEMPRE por id, y el nombre "CIELO" deja de usarse para decidir nada.
CREATE OR REPLACE FUNCTION public.portal_drive_registrar_raiz(
    p_session_token  UUID,
    p_cielo_root_id  TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_est public.estudiantes;
BEGIN
    v_est := public.evidencia_estudiante_del_portal(p_session_token);
    IF v_est IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    IF p_cielo_root_id IS NULL OR btrim(p_cielo_root_id) = '' THEN
        RETURN jsonb_build_object('error', 'Falta la carpeta CIELO');
    END IF;

    INSERT INTO public.portal_drive_conexion (
        estudiante_id, cielo_root_id, conectado_en, activo, updated_at
    )
    VALUES (v_est.id, btrim(p_cielo_root_id), NOW(), TRUE, NOW())
    ON CONFLICT (estudiante_id) DO UPDATE
       SET cielo_root_id = EXCLUDED.cielo_root_id,
           conectado_en  = EXCLUDED.conectado_en,
           activo        = TRUE,
           updated_at    = EXCLUDED.updated_at;

    RETURN jsonb_build_object('ok', TRUE, 'cielo_root_id', btrim(p_cielo_root_id));
END;
$$;

-- 4.4) Enlazar o crear la carpeta de una asignatura. Esta es la UNICA RPC que
-- puede crear estructura, y solo la llama el cliente tras una confirmacion
-- explicita del alumno.
--
-- `p_drive_folder_id` es el id que Google devolvio. Se acepta tanto si CIELO la
-- creo como si ya existia en el Drive del alumno: en los dos casos lo que se
-- guarda es el id real, y a partir de ahi no se vuelve a buscar por nombre.
CREATE OR REPLACE FUNCTION public.portal_drive_registrar_carpeta(
    p_session_token      UUID,
    p_asignatura         TEXT,
    p_asignatura_nombre  TEXT,
    p_drive_folder_id    TEXT,
    p_creado_en_drive    BOOLEAN DEFAULT FALSE
)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_est public.estudiantes;
    v_id  BIGINT;
BEGIN
    v_est := public.evidencia_estudiante_del_portal(p_session_token);
    IF v_est IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    IF p_asignatura IS NULL OR btrim(p_asignatura) = '' THEN
        RETURN jsonb_build_object('error', 'Elige una asignatura');
    END IF;
    IF p_asignatura_nombre IS NULL OR btrim(p_asignatura_nombre) = '' THEN
        RETURN jsonb_build_object('error', 'La asignatura no tiene nombre');
    END IF;
    IF p_drive_folder_id IS NULL OR btrim(p_drive_folder_id) = '' THEN
        RETURN jsonb_build_object('error', 'No se pudo crear la carpeta en Drive');
    END IF;

    -- No se comprueba que exista una conexion activa: el cliente puede haberla
    -- abierto en esta misma sesion y aun no haber cerrados el guardado. Lo que
    -- no se permite es guardar una carpeta sin token antes de tiempo, y eso lo
    -- garantiza el hecho de que el cliente solo puede obtener ese
    -- p_drive_folder_id con un token valido.
    INSERT INTO public.portal_drive_carpeta (
        estudiante_id, asignatura, asignatura_nombre,
        drive_folder_id, creado_en_drive, actualizado_at
    )
    VALUES (
        v_est.id, btrim(p_asignatura), btrim(p_asignatura_nombre),
        btrim(p_drive_folder_id), COALESCE(p_creado_en_drive, FALSE), NOW()
    )
    ON CONFLICT (estudiante_id, asignatura) DO UPDATE
       SET -- Al reconectar una asignatura se actualiza el id: si el alumno
            -- movio o renombro la carpeta, la referencia debe seguir a la
            -- carpeta que el acaba de confirmar, no quedarse en la vieja.
           drive_folder_id    = EXCLUDED.drive_folder_id,
           asignatura_nombre = EXCLUDED.asignatura_nombre,
           creado_en_drive    = EXCLUDED.creado_en_drive,
           actualizado_at     = EXCLUDED.actualizado_at
    RETURNING id INTO v_id;

    RETURN jsonb_build_object('ok', TRUE, 'id', v_id, 'drive_folder_id', btrim(p_drive_folder_id));
END;
$$;

-- 4.5) Desconectar. No se borra ninguna carpeta ni ningun archivo: el Drive del
-- alumno es suyo y CIELO solo suelta la referencia. Las evidencias ya
-- registradas conservan su drive_file_id y siguen siendo validas.
CREATE OR REPLACE FUNCTION public.portal_drive_desconectar(p_session_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_est public.estudiantes;
BEGIN
    v_est := public.evidencia_estudiante_del_portal(p_session_token);
    IF v_est IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    UPDATE public.portal_drive_conexion
       SET activo = FALSE, updated_at = NOW()
     WHERE estudiante_id = v_est.id;

    -- Las carpetas quedan linked al Drive del alumno, no a la sesion. Si vuelve
    -- a conectar, las vuelve a encontrar por el id guardado.
    RETURN jsonb_build_object('ok', TRUE);
END;
$$;

REVOKE ALL ON FUNCTION public.portal_drive_estado(UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.portal_drive_registrar_conexion(UUID, TEXT, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.portal_drive_registrar_raiz(UUID, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.portal_drive_registrar_carpeta(UUID, TEXT, TEXT, TEXT, BOOLEAN) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.portal_drive_desconectar(UUID) FROM PUBLIC, anon;

-- ----------------------------------------------------------------------------
-- 5) CREAR EVIDENCIA DESDE DRIVE
-- ----------------------------------------------------------------------------
-- Se reescribe portal_crear_evidencia de 20260926130000 para anadir
-- p_drive_carpeta_id. El DROP de la firma vieja es necesario a proposito:
-- CREATE OR REPLACE con parametros distintos NO reemplaza la funcion, crea una
-- SOBRECARGA, y quedarian dos funciones con el mismo nombre, con la llamada
-- ambigua.
DROP FUNCTION IF EXISTS public.portal_crear_evidencia(UUID, BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BIGINT, TEXT, TEXT);

CREATE OR REPLACE FUNCTION public.portal_crear_evidencia(
    p_session_token   UUID,
    p_actividad_id    BIGINT,
    p_nombre          TEXT,
    p_origen          TEXT    DEFAULT 'storage',
    p_storage_path    TEXT    DEFAULT NULL,
    p_drive_file_id   TEXT    DEFAULT NULL,
    p_drive_url       TEXT    DEFAULT NULL,
    p_mime_type       TEXT    DEFAULT NULL,
    p_tamano_bytes    BIGINT  DEFAULT NULL,
    p_thumbnail_url   TEXT    DEFAULT NULL,
    p_descripcion     TEXT    DEFAULT NULL,
    p_drive_carpeta_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_est     public.estudiantes;
    v_act     public.actividades;
    v_curso   public.cursos;
    v_carpeta public.portal_drive_carpeta;
    v_id      BIGINT;
BEGIN
    v_est := public.evidencia_estudiante_del_portal(p_session_token);
    IF v_est IS NULL THEN
        RETURN jsonb_build_object('error', 'Sesión inválida');
    END IF;

    IF p_actividad_id IS NULL THEN
        RETURN jsonb_build_object('error', 'Selecciona la actividad o ficha de la evidencia');
    END IF;

    -- Misma comprobacion que la v1: la actividad tiene que ser del curso del
    -- estudiante. Es lo que impide colgar trabajo en el curso de otro.
    SELECT a.* INTO v_act
    FROM public.actividades a
    JOIN public.cursos c ON c.id = a.curso_id
    WHERE a.id = p_actividad_id
      AND a.curso_id = v_est.curso_id
      AND a.activo IS NOT FALSE;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('error', 'La actividad no está disponible');
    END IF;

    SELECT * INTO v_curso FROM public.cursos c WHERE c.id = v_est.curso_id;

    IF p_origen NOT IN ('storage', 'drive') THEN
        RETURN jsonb_build_object('error', 'Origen de evidencia no válido');
    END IF;
    IF p_origen = 'storage' AND p_storage_path IS NULL THEN
        RETURN jsonb_build_object('error', 'Falta el archivo subido');
    END IF;
    IF p_origen = 'drive' AND p_drive_file_id IS NULL THEN
        RETURN jsonb_build_object('error', 'Falta la referencia de Google Drive');
    END IF;
    IF p_nombre IS NULL OR btrim(p_nombre) = '' THEN
        RETURN jsonb_build_object('error', 'Ponle un nombre a la evidencia');
    END IF;

    -- Si se cita una carpeta, tiene que ser del MISMO estudiante. Sin esta
    -- comprobacion un alumno podria escribir el drive_folder_id de otro y dejar
    -- la evidencia apuntando a una carpeta ajena.
    IF p_drive_carpeta_id IS NOT NULL THEN
        SELECT * INTO v_carpeta
        FROM public.portal_drive_carpeta
        WHERE id = p_drive_carpeta_id
          AND estudiante_id = v_est.id;
        IF NOT FOUND THEN
            RETURN jsonb_build_object('error', 'Esa carpeta de Drive no es tuya');
        END IF;
    END IF;

    INSERT INTO public.evidencias (
        estudiante_id, actividad_id, ficha_id, curso_id, asignatura,
        nombre, descripcion, origen, storage_path, drive_file_id, drive_url,
        mime_type, tamano_bytes, thumbnail_url, drive_carpeta_id
    )
    VALUES (
        v_est.id, v_act.id, v_act.plan_ficha_id, v_act.curso_id,
        COALESCE(v_act.asignatura, v_curso.asignatura),
        btrim(p_nombre), NULLIF(btrim(COALESCE(p_descripcion, '')), ''), p_origen,
        p_storage_path, p_drive_file_id, p_drive_url,
        p_mime_type, p_tamano_bytes, p_thumbnail_url, p_drive_carpeta_id
    )
    RETURNING id INTO v_id;

    -- El contador de la carpeta es una convenience para la UI, no una verdad.
    RETURN jsonb_build_object('id', v_id);
END;
$$;

-- ----------------------------------------------------------------------------
-- 6) GRANTS
-- ----------------------------------------------------------------------------
GRANT EXECUTE ON FUNCTION public.portal_drive_estado(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_drive_registrar_conexion(UUID, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_drive_registrar_raiz(UUID, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_drive_registrar_carpeta(UUID, TEXT, TEXT, TEXT, BOOLEAN) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_drive_desconectar(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_crear_evidencia(UUID, BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BIGINT, TEXT, TEXT, BIGINT) TO anon, authenticated;

-- El SEQUENCE de la identidad NO se concede a anon: los INSERT salen de las RPC
-- SECURITY DEFINER, que corren como owner. Concederlo abriria una via para
-- escribir en la tabla saltandose la validacion del session_token.
