-- Seed: Indicadores de 6to de Secundaria - Francés

INSERT INTO public.curr_indicadores (grado, asignatura, competencia, codigo, descripcion) VALUES
-- BC1
('6to', 'Francés', 'BC1', 'IL-1', 'Responde de forma adecuada a preguntas e indicaciones, a partir de la escucha de discursos breves y sencillos en francés con la intención de transportarse, interactuar en un restaurante, viajar, opinar, y relatar experiencias, en relación a necesidades concretas y temas cotidianos, siempre que se le hable de forma pausada y clara, y se le repita en caso de que así lo requiera.'),
('6to', 'Francés', 'BC1', 'IL-2', 'Produce textos orales y escritos en francés de forma breve y sencillo, mediante una serie de frases y oraciones enlazadas por conectores básicos para procurar servicios de transporte, interactuar en un restaurante, viajar, opinar, y relatar experiencias, con pausas y reformulaciones en lo oral y con algunos errores básicos en lo escrito.'),
('6to', 'Francés', 'BC1', 'IL-3', 'Interactúa en forma oral o escrita a través de una serie de frases y oraciones sencillas y con diversidad de vocabulario básico, enlazadas por conectores, con el propósito de transportarse, interactuar en un restaurante, viajar, opinar, y relatar experiencias, aunque con algunos errores básicos, pero con suficiente claridad para ser comprendido con un poco de esfuerzo.'),

-- BC2
('6to', 'Francés', 'BC2', 'IL-4', 'Responde de forma adecuada a preguntas e indicaciones, a partir de textos orales y escritos breves y sencillos comprendiendo de forma reflexiva y creativa la secuencia y relación lógica de los elementos donde se procura servicio de transporte, se informa sobre viajes, se relata experiencias, se interactúa en restaurantes y se da y se pide opiniones.'),
('6to', 'Francés', 'BC2', 'IL-5', 'Produce textos orales y escritos breves y sencillos con claridad y creatividad, manteniendo una secuencia clara y ordenada de las ideas, mediante el uso de conectores lógicos básicos apropiados a la relación específica de las ideas, al tema y la situación, con pausas y reformulaciones en lo oral y con posibles errores básicos en lo escrito.'),
('6to', 'Francés', 'BC2', 'IL-6', 'Interactúa en forma oral o escrita a través de una serie de oraciones breves y sencillas ordenadas de una forma lógica y presentadas de forma creativa en diferentes tipos de texto donde se procura servicio de transporte, se informa sobre viajes, se relata experiencias, se interactúa en restaurantes y se da y se pide opiniones.'),
('6to', 'Francés', 'BC2', 'IL-7', 'Responde de forma adecuada a preguntas e indicaciones sobre necesidades, situaciones y problemas de su entorno inmediato y temas que le son familiares, empleando estrategias a partir de textos orales y escritos breves y sencillos, aunque el interlocutor deba hacer cierto esfuerzo oral y escrito para comprenderle.'),
('6to', 'Francés', 'BC2', 'IL-8', 'Se comunica mediante textos orales y escritos en francés de forma clara y comprensible, para comunicar problemas inmediatos propios, de otras personas y del entorno inmediato, utilizando frases y oraciones breves y sencillas, aunque necesite reformulaciones de ideas e informaciones en ocasiones.'),
('6to', 'Francés', 'BC2', 'IL-9', 'Interactúa de forma oral y escrita para procurar servicio de transporte, informar sobre viajes, relatar experiencias, interactuar en restaurantes y dar y pedir opiniones, utilizando expresiones y frases sencillas, aunque con pausas y reformulaciones en lo oral y con posibles errores básicos en lo escrito.'),

-- BC3
('6to', 'Francés', 'BC3', 'IL-13', 'Responde de forma adecuada a preguntas e indicaciones, a partir de la escucha o lectura de textos breves y de vocabulario y expresiones básicas y sencillas sobre asuntos científicos y tecnológicos compartidos de forma personal, digital o virtual, apoyándose de imágenes y de modelos previstos.'),
('6to', 'Francés', 'BC3', 'IL-14', 'Identifica y describe aspectos científicos y tecnológicos relativos a sus actividades cotidianas y entorno inmediato, tales como servicio de transporte, información sobre viajes, relatos experiencias, interacción en restaurantes y dar y pedir opiniones, utilizando frases y oraciones breves y sencillas orales y escritas, pero con suficiente claridad para ser comprendido con un poco de esfuerzo.'),
('6to', 'Francés', 'BC3', 'IL-15', 'Interactúa en forma oral o escrita por diferentes medios físicos y electrónicos, para intercambiar información, ideas y opiniones sobre aspectos científicos y tecnológicos de su entorno inmediato, servicios, opiniones y relatos, aunque con pausas y reformulaciones en lo oral y con posibles errores básicos en lo escrito.'),
('6to', 'Francés', 'BC3', 'IL-16', 'Identifica las acciones que impactan positivamente la salud y el medioambiente en las actividades cotidianas que se realizan en su entorno inmediato.'),
('6to', 'Francés', 'BC3', 'IL-17', 'Describe información y estados del entorno inmediato, opinando sobre viajes, servicio de transporte y restaurantes para cuidar el medioambiente y la salud propia y de otras personas.'),
('6to', 'Francés', 'BC3', 'IL-18', 'Interactúa de forma adecuada en situaciones donde se promueve prácticas de hábitos saludables para las personas y amigables con el medio ambiente en diversas situaciones de comunicación en el idioma francés, utilizando frases y oraciones sencillas.'),

-- BC4
('6to', 'Francés', 'BC4', 'IL-10', 'Reconoce las diferencias individuales y la identidad social y cultural propia y de otros países relativas a transporte, viajes, relato de experiencias, interacciones en restaurantes y dar y pedir opiniones.'),
('6to', 'Francés', 'BC4', 'IL-11', 'Se comunica con las demás personas en el idioma francés, de forma oral y escrita, con cortesía, honestidad, asertividad y respeto, en intercambios sencillos en situaciones concretas de comunicación, reconociendo las diferencias individuales y la identidad social y cultural propias de la comunidad local y global.'),
('6to', 'Francés', 'BC4', 'IL-12', 'Sostiene la conversación al interactuar en forma oral o escrita, utilizando frases y oraciones sencillas para mantener la interacción de forma cortés y respetuosa a las diferencias de la cultura personal y de otras personas, relativas a transporte público, comidas, bebidas, lugares de interés, costumbres y tradiciones.'),
('6to', 'Francés', 'BC4', 'IL-19', 'Muestra empatía por los sentimientos y necesidades propios y de las demás personas.'),
('6to', 'Francés', 'BC4', 'IL-20', 'Muestra disposición para dar y obtener información, al interactuar con otras personas de forma colaborativa en distintas situaciones de comunicación.'),
('6to', 'Francés', 'BC4', 'IL-21', 'Interactúa con cortesía, respeto y asertividad al referirse a sí mismo y a otras personas en distintas situaciones de comunicación.');
