-- Seed: Indicadores de 5to de Secundaria - Francés

INSERT INTO public.curr_indicadores (grado, asignatura, competencia, codigo, descripcion) VALUES
-- BC1
('5to', 'Francés', 'BC1', 'IL-1', 'Responde de forma adecuada a preguntas e indicaciones, a partir de la escucha o lectura de textos claros, breves y sencillos, donde se describen personas y lugares, se informa sobre actividades cotidianas y de recreación, se dan instrucciones y se hacen prohibiciones e invitaciones, utilizando un repertorio creciente de vocabulario, frases y oraciones, apoyándose de imágenes y de modelos previstos.'),
('5to', 'Francés', 'BC1', 'IL-2', 'Se expresa en francés mediante una serie de frases y oraciones breves y sencillas enlazadas por conectores comunes para describir personas y lugares, informar sobre actividades cotidianas y de recreación, dar instrucciones y hacer prohibiciones e invitaciones, aunque con pausas y reformulaciones en lo oral y con posibles errores básicos en lo escrito.'),
('5to', 'Francés', 'BC1', 'IL-3', 'Interactúa de forma oral y escrita, utilizando una serie de frases y oraciones breves y sencillas y con diversidad de vocabulario básico referente a la descripción de personas y lugares, información sobre actividades cotidianas y de recreación, instrucciones, prohibiciones e invitaciones, pero con suficiente claridad para ser comprendido con un poco de esfuerzo.'),

-- BC2
('5to', 'Francés', 'BC2', 'IL-4', 'Responde a preguntas e indicaciones, utilizando el pensamiento lógico verbal, creativo y crítico para comprender la información contenida en mensajes orales y escritos breves y sencillos en francés referentes a necesidades concretas y temas cotidianos.'),
('5to', 'Francés', 'BC2', 'IL-5', 'Se expresa en francés a través de frases y oraciones breves y sencillas con creatividad y mediante una estructura lógica básica, enlazadas por conectores comunes, con pausas y reformulaciones en lo oral y con posibles errores básicos en lo escrito.'),
('5to', 'Francés', 'BC2', 'IL-6', 'Interactúa de forma oral y escrita siguiendo la lógica de la interacción y el contexto inmediato, expresándose mediante frases y oraciones breves y sencillas con creatividad y pensamiento reflexivo.'),
('5to', 'Francés', 'BC2', 'IL-7', 'Responde acorde a preguntas e indicaciones, a partir de información sencilla contenida en textos orales o escritos sobre necesidades, situaciones y problemas cotidianos o del entorno próximo.'),
('5to', 'Francés', 'BC2', 'IL-8', 'Se expresa de forma oral y escrita, utilizando expresiones breves y sencillas para describir de forma clara, ideas, elementos, personas y acciones relativas a necesidades, problemas o situaciones de su entorno inmediato.'),
('5to', 'Francés', 'BC2', 'IL-9', 'Interactúa en intercambios comunicativos breves y sencillos, identificando problemas y situaciones variadas de sus actividades cotidianas y de su entorno inmediato, planteando opciones justas para enfrentar la situación, utilizando expresiones y frases sencillas, aunque con pausas y reformulaciones en lo oral y con posibles errores básicos en lo escrito.'),

-- BC3
('5to', 'Francés', 'BC3', 'IL-13', 'Responde de forma adecuada a preguntas e indicaciones a partir de la escucha o lectura de textos breves y de vocabulario y expresiones básicas y sencillas sobre asuntos científicos y tecnológicos compartidos de forma personal, digital o virtual, apoyándose de imágenes y de modelos previstos.'),
('5to', 'Francés', 'BC3', 'IL-14', 'Identifica y describe aspectos científicos y tecnológicos relativos a sus actividades cotidianas y entorno inmediato, tales como la descripción de personas y lugares, actividades cotidianas y de recreación, instrucciones y hacer prohibiciones e invitaciones, utilizando frases y oraciones breves y sencillas orales y escritas, pero con suficiente claridad para ser comprendido con un poco de esfuerzo.'),
('5to', 'Francés', 'BC3', 'IL-15', 'Interactúa en forma oral o escrita por diferentes medios físicos y electrónicos, para intercambiar información, ideas y opiniones sobre aspectos científicos y tecnológicos del entorno inmediato, actividades.'),
('5to', 'Francés', 'BC3', 'IL-16', 'Responde de forma favorable a la preservación del medioambiente y la salud ante preguntas e indicaciones sobre información de las personas, el entorno y sus actividades cotidianas, utilizando frases y oraciones breves y sencillas orales y escritas.'),
('5to', 'Francés', 'BC3', 'IL-17', 'Ofrece información, opiniones e instrucciones sobre acciones que impactan positivamente el medioambiente y la salud propia y de otras personas, utilizando frases y oraciones breves y sencillas orales y escritas.'),
('5to', 'Francés', 'BC3', 'IL-18', 'Interactúa para compartir información personal, de su entorno inmediato y de actividades cotidianas, mostrando preferencia por aquellas que impactan positivamente la salud y el medioambiente, utilizando frases y oraciones breves y sencillas orales y escritas.'),

-- BC4
('5to', 'Francés', 'BC4', 'IL-10', 'Participa de forma activa, con escucha atenta y respetuosa en las interacciones formativas e informativas que realiza, identificando aspectos de la identidad social y cultural propia y de otros países, con actitud de aceptación y asertividad.'),
('5to', 'Francés', 'BC4', 'IL-11', 'Expresa preferencias y puntos de vista de forma oral o escrita, con actitud respetuosa, honesta, cortés y asertiva, teniendo en cuenta las diferencias individuales y la cultura propia y de otras personas.'),
('5to', 'Francés', 'BC4', 'IL-12', 'Interactúa en un plano de cortesía, asertividad y respeto tomando en cuenta las diferencias individuales y la identidad social y cultural propia y de otras personas relativos a rasgos físicos, lugares de interés, tradiciones, celebraciones, tiempo libre y recreación.'),
('5to', 'Francés', 'BC4', 'IL-19', 'Identifica respetuosamente a las personas por su apariencia y forma de ser preferencias sobre actividades cotidianas y lugares, en un plano de cortesía, aceptación y asertividad ante sí mismo y los demás.'),
('5to', 'Francés', 'BC4', 'IL-20', 'Comparte información sobre su identidad personal y preferencias sobre lugares y actividades cotidianas con humildad, cortesía, asertividad y respeto.'),
('5to', 'Francés', 'BC4', 'IL-21', 'Interactúa con cortesía, honestidad, asertividad y respeto, en intercambios orales y escritos de información, actividades recreativas, prohibiciones, órdenes e instrucciones.');
