-- Seed: Indicadores de 2do de Secundaria - Lenguas Extranjeras (Francés)

INSERT INTO public.curr_indicadores (grado, asignatura, competencia, codigo, descripcion) VALUES
-- BC1
('2do', 'Lenguas Extranjeras (Francés)', 'BC1', 'IL-1', 'Responde de manera adecuada a preguntas e indicaciones, a partir de textos orales o escritos breves y sencillos, compuestos por un repertorio muy limitado de vocabulario y expresiones ensayadas en el idioma francés, relativos a información personal básica, actividades cotidianas, preferencias y descripción de viviendas, releyendo cuando sea necesario.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC1', 'IL-2', 'Produce textos orales y escritos muy breves y sencillos que requieren cierto esfuerzo para ser comprendidos, usualmente compuestos por un repertorio limitado de vocabulario y expresiones básicas donde se tratan brevemente informaciones personales, propias y de otras personas, actividades cotidianas, descripción del entorno inmediato y preferencias, apoyándose en experiencias previas, imágenes y estrategias compensatorias.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC1', 'IL-3', 'Interactúa de forma oral y escrita, utilizando un repertorio ensayado de vocabulario y expresiones muy breves y sencillas, donde se identifica e identifica a otras personas, y donde describe sus actividades cotidianas y sus preferencias, necesitando ayuda de su interlocutor para comprender y hacerse comprender.'),

-- BC2
('2do', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-4', 'Utiliza el pensamiento lógico-verbal para comprender expresiones básicas en textos orales y escritos muy breves y senillos sobre identificación personal, actividades inmediatas y descripción de su entorno, releyendo cuando sea necesario y ayudándose de las ilustraciones y otros elementos textuales y paratextuales del contexto.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-5', 'Presenta de forma lógica y creativa la estructura y secuencia de ideas, empleando estrategias de desempeño y pensamiento creativo, tales como acompañar con dibujos, dramatizar, cantar, entre otros, aunque requiera esfuerzo poder comprender las frases y oraciones breves y sencillas que expresa en forma oral o escrita.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-6', 'Interactúa de forma sencilla oral y escrita muy breve y sencilla sobre situaciones de identificación personal, descripción de su entorno, actividades cotidianas y gustos y preferencias, utilizando el pensamiento lógico-verbal para estructurar y seguir la secuencia de expresiones ensayadas y el pensamiento creativo para realizar el intercambio en la situación planteada.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-7', 'Responde de forma adecuada a preguntas en indicaciones simples de información específica, tendentes a la resolución de situaciones y problemas inmediatos, a partir de textos orales y escritos simples donde se comparte información personal, y se describe actividades cotidianas, la vivienda y los gustos y preferencias.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-8', 'Presenta información breve sobre situaciones y problemas que lo requieren, utilizando frases y oraciones escritas, y de elementos orales practicados en colocación sucesiva, que se comprenden al compartir información personal y describir actividades cotidianas, la vivienda y los gustos y preferencias.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-9', 'Interactúa de forma muy breve y sencilla para compartir información básica tendente a resolver situaciones o problemas planteados en su entorno cotidiano inmediato, tales como información personal básica, descripción de vivienda, actividades cotidianas y gustos y preferencias, utilizando un repertorio limitado de vocabulario y expresiones con ayuda de su interlocutor.'),

-- BC3
('2do', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-13', 'Localiza información referente a aspectos de la ciencia y la tecnología, en la identificación personal de otras personas, en sus actividades cotidianas, gustos y preferencias y descripción de viviendas, siempre que el texto esté compuesto por frases y oraciones comunes sencillas y pueda releer o escuchar de nuevo cuando sea necesario.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-14', 'Se refiere a aspectos de la ciencia y la tecnología, a partir de un repertorio limitado de expresiones orales y escritas ensayadas, relativas a identificación personal, descripción de actividades cotidianas, viviendas, gustos y preferencias.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-15', 'Interactúa en forma oral y escrita empleando aspectos científicos y tecnológicos propios de la identificación de las personas, gustos y preferencias, vivienda y actividades cotidianas, a través de un repertorio limitado de expresiones ensayadas.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-16', 'Responde a preguntas e indicaciones de reflexión sobre las opciones que impactan positivamente la salud y el medio ambiente, a partir de la escucha lectura de textos breves sobre situaciones inmediatas de comunicación.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-17', 'Escribe textos orales y escritos muy breves y sencillos, en los que muestra preferencia por opciones favorables para su salud, la de otras personas, y el medioambiente.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-18', 'Interactúa mostrando preferencia por opciones beneficiosas para el medioambiente y la salud, a partir de expresiones breves.'),

-- BC4
('2do', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-10', 'Responde de forma adecuada ante las expresiones de cortesía y respeto, identificándolas al compartir información personal, sus actividades cotidianas, descripción de su vivienda y sus preferencias.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-11', 'Se expresa con cortesía, respeto y asertividad, al compartir información personal, sus actividades cotidianas, descripción de su vivienda y sus preferencias, en textos orales y escritos muy breves y sencillos'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-12', 'Interactúa de forma oral y escrita con expresiones básicas de cortesía, tolerancia y respeto a las diferencias individuales, costumbres y cultura de las demás personas.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-19', 'Responde de forma adecuada y en un plano de cortesía, honestidad, aceptación, asertividad y respeto, a preguntas e indicaciones, a partir de la escucha o lectura de textos sencillos que contienen información personal básica, y descripción de actividades cotidianas y objetos de su vivienda y entorno.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-20', 'Se expresa en forma oral y escrita con cortesía, honestidad, aceptación y respeto por la identidad personal y modo de vida de las demás personas, utilizando frases simples en el idioma francés.'),
('2do', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-21', 'Interactúa de forma oral y escrita con cortesía, actitud de respeto, aceptación y asertividad en intercambios sencillos en el idioma francés.');
