-- Seed: Indicadores de 3ro de Secundaria - Lenguas Extranjeras (Francés)

INSERT INTO public.curr_indicadores (grado, asignatura, competencia, codigo, descripcion) VALUES
-- BC1
('3ro', 'Lenguas Extranjeras (Francés)', 'BC1', 'IL-1', 'Responde de manera adecuada a preguntas e indicaciones a partir de textos cortos orales o escritos, compuestos por un repertorio creciente de vocabulario y expresiones practicadas en el idioma francés, relativos a información personal básica, descripción de actividades que se llevan a cabo, así como también de planes futuros, volviendo a escuchar y releyendo cuando sea necesario.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC1', 'IL-2', 'Produce textos orales y escritos muy breves y sencillos que requieren cierto esfuerzo para ser comprendidos, usualmente compuestos por un repertorio limitado de vocabulario y expresiones básicas sobre informaciones personales, ubicación de lugares y condición atmosférica, actividades que se están llevando a cabo y planes futuros, apoyándose en experiencias previas y strategies compensatorias.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC1', 'IL-3', 'Interactúa de forma oral y escrita, utilizando un repertorio ensayado de vocabulario y expresiones muy breves y sencillas, donde se comparte la ubicación de lugares y sus condiciones atmosféricas, actividades que se están llevando a cabo y planes futuros, necesitando ayuda de su interlocutor para comprender y hacerse comprender.'),

-- BC2
('3ro', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-4', 'Utiliza el pensamiento lógico-verbal para comprender expresiones básicas en textos orales y escritos muy breves y sencillos sobre descripción de la ubicación y las condiciones atmosféricas de su entorno, así como de actividades que lleva a cabo y planes futuros, releyendo cuando sea necesario y ayudándose de las ilustraciones y otros elementos textuales y paratextuales del contexto.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-5', 'Presenta de forma lógica y creativa la estructura y secuencia de ideas, empleando estrategias de desempeño y pensamiento creativo, tales como acompañar con dibujos, dramatizar, cantar, entre otros, aunque requiera esfuerzo poder comprender las frases y oraciones breves y sencillas que expresan en forma oral o escrita.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-6', 'Interactúa de forma oral y escrita breve y sencilla sobre situaciones cotidianas, descripción de su entorno, actividades presentes y planes futuros, utilizando el pensamiento lógico-verbal para estructurar y seguir la secuencia de expresiones ensayadas y el pensamiento creativo al realizar el intercambio en la situación planteada.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-7', 'Responde de forma adecuada a preguntas en indicaciones simples de información específica, tendentes a la resolución de situaciones y problemas inmediatos, a partir de textos orales y escritos muy breves y sencillos donde se comparte información personal, y se describe actividades presentes y planes futuros, tomando en cuenta lugares, ubicación y condiciones atmosféricas.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-8', 'Presenta información breve y sencilla sobre situaciones y problemas de su entorno, utilizando frases y oraciones escritas sueltas, y de elementos orales ensayados en colocación sucesiva, que se comprenden con cierto esfuerzo al compartir información, actividades presentes, planes futuros, además de descripción de lugares y condiciones atmosféricas y viviendas.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC2', 'IL-9', 'Interactúa de forma muy breve y sencilla para compartir información básica tendente a resolver situaciones o problemas planteados en su entorno cotidiano inmediato, tales como la identificación de personas, actividades variadas, ubicación de lugares y planes futuros, utilizando un repertorio limitado de vocabulario y expresiones con ayuda de su interlocutor.'),

-- BC3
('3ro', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-13', 'Localiza información básica referente a aspectos de la ciencia y la tecnología, en la identificación y la descripción de objetos personas, lugares, actividades, condiciones atmosféricas y planes futuros, a partir de textos compuesto por frases y oraciones comunes muy breves y sencillas que pueda releer o escuchar de nuevo cuando sea necesario.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-14', 'Se refiere a aspectos de la ciencia y la tecnología, a partir de un repertorio limitado de expresiones orales y escritas ensayadas, relativas a descripción de objetos, personas, actividades, condiciones atmosféricas y planes futuros, que se pueden comprender, aunque con cierto esfuerzo.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-15', 'Interactúa en forma oral y escrita sobre temas científicos y tecnológicos en la descripción de objetos, personas, lugares, y condiciones atmosféricas, además de actividades que se están llevando a cabo y planes futuros, utilizando un repertorio limitado de expresiones ensayadas y con ayuda de su interlocutor.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-16', 'Responde a preguntas e indicaciones sobre las opciones que impactan positivamente la salud y el medio ambiente, a partir de la escucha o lectura de textos muy breves y sencillos sobre descripción de objetos, personas, lugares, condiciones atmosféricas, actividades que se realizan y planes futuros.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-17', 'Escribe textos orales y escritos muy breves y sencillos, en los que muestra preferencia por opciones favorables para su salud, la de otras personas, y el medio ambiente, al describir objetos, personas, lugares, condiciones atmosféricas, actividades que se realizan y planes futuros.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC3', 'IL-18', 'Interactúa con ayuda de su interlocutor para comprender y poder ser comprendido, mostrando preferencia por opciones beneficiosas para el medio ambiente y la salud, a partir de expresiones muy sencillas y breves donde se describen objetos, personas, lugares, condiciones atmosféricas, actividades que se realizan y planes futuros.'),

-- BC4
('3ro', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-10', 'Responde de forma adecuada ante las expresiones de cortesía, respeto y asertividad, identificándolas y reciprocándolas al compartir información personal, planes futuros, descripción de lugares de su comunidad, incluyendo la ubicación y el clima.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-11', 'Se expresa con cortesía, respeto y asertividad, al compartir información personal básica, describir actividades cotidianas, condiciones atmosféricas y planes, además de personas, lugares y objetos, en textos orales y escritos muy breves y sencillos.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-12', 'Interactúa de forma oral y escrita con expresiones muy básicas de cortesía, asertividad y respeto a las diferencias individuales, costumbres y cultura de las demás personas en su entorno inmediato y próximo.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-19', 'Responde de forma adecuada a preguntas e indicaciones, en un plano de cortesía, honestidad, aceptación, asertividad y respeto, a partir de la información contenida en textos orales y escritos muy breves y sencillos en el idioma francés.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-20', 'Se expresa en forma oral y escrita con cortesía, honestidad, aceptación, asertividad y respeto por la identidad personal y modo de vida de las demás personas, sus procedencias y planes futuros, utilizando frases muy breves y sencillas en el idioma francés.'),
('3ro', 'Lenguas Extranjeras (Francés)', 'BC4', 'IL-21', 'Interactúa de forma oral y escrita con cortesía, actitud de respeto, aceptación y asertividad en intercambios muy sencillos en el idioma francés donde se comparte información personal sobre actividades y planes futuros.');
